version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google.golang.org/api
    versions:
    - 0.37.0
    - 0.38.0
    - 0.39.0
    - 0.40.0
    - 0.41.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: cloud.google.com/go
    versions:
    - 0.75.0
    - 0.76.0
    - 0.77.0
    - 0.78.0
    - 0.79.0
    - 0.80.0
  - dependency-name: cloud.google.com/go/storage
    versions:
    - 1.12.0
    - 1.13.0
    - 1.14.0
  - dependency-name: go.opencensus.io
    versions:
    - 0.22.5
    - 0.22.6
  - dependency-name: github.com/mattn/go-sqlite3
    versions:
    - 1.14.6
  - dependency-name: github.com/prometheus/client_golang
    versions:
    - 1.9.0
  - dependency-name: github.com/volatiletech/sqlboiler/v4
    versions:
    - 4.4.0
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
