steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$${_DOCKER_HUB_USERNAME} --password=$${_DOCKER_HUB_PASSWORD}']
    secretEnv: ['_DOCKER_HUB_USERNAME', '_DOCKER_HUB_PASSWORD']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'twcclan/goback', '.']
secrets:
- kmsKeyName: projects/admin-181512/locations/global/keyRings/cloud-build/cryptoKeys/env-secrets
  secretEnv:
    _DOCKER_HUB_PASSWORD: CiQAeqcjw5dh4s71U3MdwBLmDK0ro/ltiv60UhQpkN514Lq4SNkSPQDtxcT58g8Qc5YkAuYFahQouD6Q8u+8Znopa+Klb6mAQRTJamroObphwBdwDreYSwbxme7XL94SWIAG4YA=
    _DOCKER_HUB_USERNAME: CiQAeqcjw/lb2S82g76EQ7rNsLo4GAAyyt0VrHi11Yuq2PLNP1kSMwDtxcT5/EwTFlrbpzAwLQiDyptttzuItghaVj5bDPavuhz+IdiEqThAwuHvm4DLgHL1DQ==
images: ['twcclan/goback']
timeout: 1200s