// Code generated by ent, DO NOT EDIT.

package reindex

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gobackio/goback/index/sql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Reindex {
	return predicate.Reindex(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Reindex {
	return predicate.Reindex(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Reindex {
	return predicate.Reindex(sql.FieldContainsFold(FieldID, id))
}

// Churn applies equality check predicate on the "churn" field. It's identical to ChurnEQ.
func Churn(v int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldEQ(FieldChurn, v))
}

// StatsReset applies equality check predicate on the "stats_reset" field. It's identical to StatsResetEQ.
func StatsReset(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldEQ(FieldStatsReset, v))
}

// ReindexedAt applies equality check predicate on the "reindexed_at" field. It's identical to ReindexedAtEQ.
func ReindexedAt(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldEQ(FieldReindexedAt, v))
}

// ChurnEQ applies the EQ predicate on the "churn" field.
func ChurnEQ(v int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldEQ(FieldChurn, v))
}

// ChurnNEQ applies the NEQ predicate on the "churn" field.
func ChurnNEQ(v int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldNEQ(FieldChurn, v))
}

// ChurnIn applies the In predicate on the "churn" field.
func ChurnIn(vs ...int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldIn(FieldChurn, vs...))
}

// ChurnNotIn applies the NotIn predicate on the "churn" field.
func ChurnNotIn(vs ...int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldNotIn(FieldChurn, vs...))
}

// ChurnGT applies the GT predicate on the "churn" field.
func ChurnGT(v int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldGT(FieldChurn, v))
}

// ChurnGTE applies the GTE predicate on the "churn" field.
func ChurnGTE(v int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldGTE(FieldChurn, v))
}

// ChurnLT applies the LT predicate on the "churn" field.
func ChurnLT(v int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldLT(FieldChurn, v))
}

// ChurnLTE applies the LTE predicate on the "churn" field.
func ChurnLTE(v int64) predicate.Reindex {
	return predicate.Reindex(sql.FieldLTE(FieldChurn, v))
}

// StatsResetEQ applies the EQ predicate on the "stats_reset" field.
func StatsResetEQ(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldEQ(FieldStatsReset, v))
}

// StatsResetNEQ applies the NEQ predicate on the "stats_reset" field.
func StatsResetNEQ(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldNEQ(FieldStatsReset, v))
}

// StatsResetIn applies the In predicate on the "stats_reset" field.
func StatsResetIn(vs ...time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldIn(FieldStatsReset, vs...))
}

// StatsResetNotIn applies the NotIn predicate on the "stats_reset" field.
func StatsResetNotIn(vs ...time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldNotIn(FieldStatsReset, vs...))
}

// StatsResetGT applies the GT predicate on the "stats_reset" field.
func StatsResetGT(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldGT(FieldStatsReset, v))
}

// StatsResetGTE applies the GTE predicate on the "stats_reset" field.
func StatsResetGTE(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldGTE(FieldStatsReset, v))
}

// StatsResetLT applies the LT predicate on the "stats_reset" field.
func StatsResetLT(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldLT(FieldStatsReset, v))
}

// StatsResetLTE applies the LTE predicate on the "stats_reset" field.
func StatsResetLTE(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldLTE(FieldStatsReset, v))
}

// StatsResetIsNil applies the IsNil predicate on the "stats_reset" field.
func StatsResetIsNil() predicate.Reindex {
	return predicate.Reindex(sql.FieldIsNull(FieldStatsReset))
}

// StatsResetNotNil applies the NotNil predicate on the "stats_reset" field.
func StatsResetNotNil() predicate.Reindex {
	return predicate.Reindex(sql.FieldNotNull(FieldStatsReset))
}

// ReindexedAtEQ applies the EQ predicate on the "reindexed_at" field.
func ReindexedAtEQ(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldEQ(FieldReindexedAt, v))
}

// ReindexedAtNEQ applies the NEQ predicate on the "reindexed_at" field.
func ReindexedAtNEQ(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldNEQ(FieldReindexedAt, v))
}

// ReindexedAtIn applies the In predicate on the "reindexed_at" field.
func ReindexedAtIn(vs ...time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldIn(FieldReindexedAt, vs...))
}

// ReindexedAtNotIn applies the NotIn predicate on the "reindexed_at" field.
func ReindexedAtNotIn(vs ...time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldNotIn(FieldReindexedAt, vs...))
}

// ReindexedAtGT applies the GT predicate on the "reindexed_at" field.
func ReindexedAtGT(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldGT(FieldReindexedAt, v))
}

// ReindexedAtGTE applies the GTE predicate on the "reindexed_at" field.
func ReindexedAtGTE(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldGTE(FieldReindexedAt, v))
}

// ReindexedAtLT applies the LT predicate on the "reindexed_at" field.
func ReindexedAtLT(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldLT(FieldReindexedAt, v))
}

// ReindexedAtLTE applies the LTE predicate on the "reindexed_at" field.
func ReindexedAtLTE(v time.Time) predicate.Reindex {
	return predicate.Reindex(sql.FieldLTE(FieldReindexedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Reindex) predicate.Reindex {
	return predicate.Reindex(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Reindex) predicate.Reindex {
	return predicate.Reindex(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Reindex) predicate.Reindex {
	return predicate.Reindex(sql.NotPredicates(p))
}
