// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/twcclan/goback/index/sql/ent/archive"
	"github.com/twcclan/goback/index/sql/ent/object"
)

// Object is the model entity for the Object schema.
type Object struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Ref holds the value of the "ref" field.
	Ref []byte `json:"ref,omitempty"`
	// ArchiveID holds the value of the "archive_id" field.
	ArchiveID string `json:"archive_id,omitempty"`
	// Start holds the value of the "start" field.
	Start uint32 `json:"start,omitempty"`
	// Length holds the value of the "length" field.
	Length uint32 `json:"length,omitempty"`
	// Type holds the value of the "type" field.
	Type uint32 `json:"type,omitempty"`
	// CarriedTime holds the value of the "carried_time" field.
	CarriedTime int64 `json:"carried_time,omitempty"`
	// CarriedOffset holds the value of the "carried_offset" field.
	CarriedOffset uint32 `json:"carried_offset,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ObjectQuery when eager-loading is set.
	Edges        ObjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ObjectEdges holds the relations/edges for other nodes in the graph.
type ObjectEdges struct {
	// Archive holds the value of the archive edge.
	Archive *Archive `json:"archive,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ArchiveOrErr returns the Archive value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ObjectEdges) ArchiveOrErr() (*Archive, error) {
	if e.Archive != nil {
		return e.Archive, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: archive.Label}
	}
	return nil, &NotLoadedError{edge: "archive"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Object) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case object.FieldRef:
			values[i] = new([]byte)
		case object.FieldID, object.FieldStart, object.FieldLength, object.FieldType, object.FieldCarriedTime, object.FieldCarriedOffset:
			values[i] = new(sql.NullInt64)
		case object.FieldArchiveID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Object fields.
func (_m *Object) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case object.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case object.FieldRef:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ref", values[i])
			} else if value != nil {
				_m.Ref = *value
			}
		case object.FieldArchiveID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field archive_id", values[i])
			} else if value.Valid {
				_m.ArchiveID = value.String
			}
		case object.FieldStart:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start", values[i])
			} else if value.Valid {
				_m.Start = uint32(value.Int64)
			}
		case object.FieldLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field length", values[i])
			} else if value.Valid {
				_m.Length = uint32(value.Int64)
			}
		case object.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = uint32(value.Int64)
			}
		case object.FieldCarriedTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field carried_time", values[i])
			} else if value.Valid {
				_m.CarriedTime = value.Int64
			}
		case object.FieldCarriedOffset:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field carried_offset", values[i])
			} else if value.Valid {
				_m.CarriedOffset = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Object.
// This includes values selected through modifiers, order, etc.
func (_m *Object) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryArchive queries the "archive" edge of the Object entity.
func (_m *Object) QueryArchive() *ArchiveQuery {
	return NewObjectClient(_m.config).QueryArchive(_m)
}

// Update returns a builder for updating this Object.
// Note that you need to call Object.Unwrap() before calling this method if this Object
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Object) Update() *ObjectUpdateOne {
	return NewObjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Object entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Object) Unwrap() *Object {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Object is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Object) String() string {
	var builder strings.Builder
	builder.WriteString("Object(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ref=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ref))
	builder.WriteString(", ")
	builder.WriteString("archive_id=")
	builder.WriteString(_m.ArchiveID)
	builder.WriteString(", ")
	builder.WriteString("start=")
	builder.WriteString(fmt.Sprintf("%v", _m.Start))
	builder.WriteString(", ")
	builder.WriteString("length=")
	builder.WriteString(fmt.Sprintf("%v", _m.Length))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("carried_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.CarriedTime))
	builder.WriteString(", ")
	builder.WriteString("carried_offset=")
	builder.WriteString(fmt.Sprintf("%v", _m.CarriedOffset))
	builder.WriteByte(')')
	return builder.String()
}

// Objects is a parsable slice of Object.
type Objects []*Object
