// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gobackio/goback/index/sql/ent/reindex"
)

// Reindex is the model entity for the Reindex schema.
type Reindex struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Churn holds the value of the "churn" field.
	Churn int64 `json:"churn,omitempty"`
	// StatsReset holds the value of the "stats_reset" field.
	StatsReset *time.Time `json:"stats_reset,omitempty"`
	// ReindexedAt holds the value of the "reindexed_at" field.
	ReindexedAt  time.Time `json:"reindexed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Reindex) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reindex.FieldChurn:
			values[i] = new(sql.NullInt64)
		case reindex.FieldID:
			values[i] = new(sql.NullString)
		case reindex.FieldStatsReset, reindex.FieldReindexedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Reindex fields.
func (_m *Reindex) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reindex.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case reindex.FieldChurn:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field churn", values[i])
			} else if value.Valid {
				_m.Churn = value.Int64
			}
		case reindex.FieldStatsReset:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field stats_reset", values[i])
			} else if value.Valid {
				_m.StatsReset = new(time.Time)
				*_m.StatsReset = value.Time
			}
		case reindex.FieldReindexedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reindexed_at", values[i])
			} else if value.Valid {
				_m.ReindexedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Reindex.
// This includes values selected through modifiers, order, etc.
func (_m *Reindex) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Reindex.
// Note that you need to call Reindex.Unwrap() before calling this method if this Reindex
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Reindex) Update() *ReindexUpdateOne {
	return NewReindexClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Reindex entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Reindex) Unwrap() *Reindex {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Reindex is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Reindex) String() string {
	var builder strings.Builder
	builder.WriteString("Reindex(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("churn=")
	builder.WriteString(fmt.Sprintf("%v", _m.Churn))
	builder.WriteString(", ")
	if v := _m.StatsReset; v != nil {
		builder.WriteString("stats_reset=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("reindexed_at=")
	builder.WriteString(_m.ReindexedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Reindices is a parsable slice of Reindex.
type Reindices []*Reindex
