// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twcclan/goback/index/sql/ent/archive"
	"github.com/twcclan/goback/index/sql/ent/session"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAgentID sets the "agent_id" field.
func (_c *SessionCreate) SetAgentID(v string) *SessionCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetBackupSet sets the "backup_set" field.
func (_c *SessionCreate) SetBackupSet(v string) *SessionCreate {
	_c.mutation.SetBackupSet(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SessionCreate) SetStartedAt(v time.Time) *SessionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *SessionCreate) SetLastSeen(v time.Time) *SessionCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetRestoreRef sets the "restore_ref" field.
func (_c *SessionCreate) SetRestoreRef(v []byte) *SessionCreate {
	_c.mutation.SetRestoreRef(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SessionCreate) SetID(v string) *SessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddArchiveIDs adds the "archives" edge to the Archive entity by IDs.
func (_c *SessionCreate) AddArchiveIDs(ids ...string) *SessionCreate {
	_c.mutation.AddArchiveIDs(ids...)
	return _c
}

// AddArchives adds the "archives" edges to the Archive entity.
func (_c *SessionCreate) AddArchives(v ...*Archive) *SessionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddArchiveIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Session.agent_id"`)}
	}
	if _, ok := _c.mutation.BackupSet(); !ok {
		return &ValidationError{Name: "backup_set", err: errors.New(`ent: missing required field "Session.backup_set"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Session.started_at"`)}
	}
	if _, ok := _c.mutation.LastSeen(); !ok {
		return &ValidationError{Name: "last_seen", err: errors.New(`ent: missing required field "Session.last_seen"`)}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Session.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(session.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.BackupSet(); ok {
		_spec.SetField(session.FieldBackupSet, field.TypeString, value)
		_node.BackupSet = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(session.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = value
	}
	if value, ok := _c.mutation.RestoreRef(); ok {
		_spec.SetField(session.FieldRestoreRef, field.TypeBytes, value)
		_node.RestoreRef = value
	}
	if nodes := _c.mutation.ArchivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.ArchivesTable,
			Columns: []string{session.ArchivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Session.Create().
//		SetAgentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SessionUpsert) {
//			SetAgentID(v+v).
//		}).
//		Exec(ctx)
func (_c *SessionCreate) OnConflict(opts ...sql.ConflictOption) *SessionUpsertOne {
	_c.conflict = opts
	return &SessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SessionCreate) OnConflictColumns(columns ...string) *SessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SessionUpsertOne{
		create: _c,
	}
}

type (
	// SessionUpsertOne is the builder for "upsert"-ing
	//  one Session node.
	SessionUpsertOne struct {
		create *SessionCreate
	}

	// SessionUpsert is the "OnConflict" setter.
	SessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetAgentID sets the "agent_id" field.
func (u *SessionUpsert) SetAgentID(v string) *SessionUpsert {
	u.Set(session.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *SessionUpsert) UpdateAgentID() *SessionUpsert {
	u.SetExcluded(session.FieldAgentID)
	return u
}

// SetBackupSet sets the "backup_set" field.
func (u *SessionUpsert) SetBackupSet(v string) *SessionUpsert {
	u.Set(session.FieldBackupSet, v)
	return u
}

// UpdateBackupSet sets the "backup_set" field to the value that was provided on create.
func (u *SessionUpsert) UpdateBackupSet() *SessionUpsert {
	u.SetExcluded(session.FieldBackupSet)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *SessionUpsert) SetStartedAt(v time.Time) *SessionUpsert {
	u.Set(session.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SessionUpsert) UpdateStartedAt() *SessionUpsert {
	u.SetExcluded(session.FieldStartedAt)
	return u
}

// SetLastSeen sets the "last_seen" field.
func (u *SessionUpsert) SetLastSeen(v time.Time) *SessionUpsert {
	u.Set(session.FieldLastSeen, v)
	return u
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *SessionUpsert) UpdateLastSeen() *SessionUpsert {
	u.SetExcluded(session.FieldLastSeen)
	return u
}

// SetRestoreRef sets the "restore_ref" field.
func (u *SessionUpsert) SetRestoreRef(v []byte) *SessionUpsert {
	u.Set(session.FieldRestoreRef, v)
	return u
}

// UpdateRestoreRef sets the "restore_ref" field to the value that was provided on create.
func (u *SessionUpsert) UpdateRestoreRef() *SessionUpsert {
	u.SetExcluded(session.FieldRestoreRef)
	return u
}

// ClearRestoreRef clears the value of the "restore_ref" field.
func (u *SessionUpsert) ClearRestoreRef() *SessionUpsert {
	u.SetNull(session.FieldRestoreRef)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(session.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SessionUpsertOne) UpdateNewValues() *SessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(session.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Session.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SessionUpsertOne) Ignore() *SessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SessionUpsertOne) DoNothing() *SessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SessionCreate.OnConflict
// documentation for more info.
func (u *SessionUpsertOne) Update(set func(*SessionUpsert)) *SessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *SessionUpsertOne) SetAgentID(v string) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateAgentID() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateAgentID()
	})
}

// SetBackupSet sets the "backup_set" field.
func (u *SessionUpsertOne) SetBackupSet(v string) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetBackupSet(v)
	})
}

// UpdateBackupSet sets the "backup_set" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateBackupSet() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateBackupSet()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *SessionUpsertOne) SetStartedAt(v time.Time) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateStartedAt() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateStartedAt()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *SessionUpsertOne) SetLastSeen(v time.Time) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateLastSeen() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateLastSeen()
	})
}

// SetRestoreRef sets the "restore_ref" field.
func (u *SessionUpsertOne) SetRestoreRef(v []byte) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetRestoreRef(v)
	})
}

// UpdateRestoreRef sets the "restore_ref" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateRestoreRef() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateRestoreRef()
	})
}

// ClearRestoreRef clears the value of the "restore_ref" field.
func (u *SessionUpsertOne) ClearRestoreRef() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.ClearRestoreRef()
	})
}

// Exec executes the query.
func (u *SessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SessionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SessionUpsertOne.ID is not supported by MySQL driver. Use SessionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SessionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
	conflict []sql.ConflictOption
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Session.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SessionUpsert) {
//			SetAgentID(v+v).
//		}).
//		Exec(ctx)
func (_c *SessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SessionUpsertBulk {
	_c.conflict = opts
	return &SessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SessionCreateBulk) OnConflictColumns(columns ...string) *SessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SessionUpsertBulk{
		create: _c,
	}
}

// SessionUpsertBulk is the builder for "upsert"-ing
// a bulk of Session nodes.
type SessionUpsertBulk struct {
	create *SessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(session.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SessionUpsertBulk) UpdateNewValues() *SessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(session.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SessionUpsertBulk) Ignore() *SessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SessionUpsertBulk) DoNothing() *SessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SessionCreateBulk.OnConflict
// documentation for more info.
func (u *SessionUpsertBulk) Update(set func(*SessionUpsert)) *SessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *SessionUpsertBulk) SetAgentID(v string) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateAgentID() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateAgentID()
	})
}

// SetBackupSet sets the "backup_set" field.
func (u *SessionUpsertBulk) SetBackupSet(v string) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetBackupSet(v)
	})
}

// UpdateBackupSet sets the "backup_set" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateBackupSet() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateBackupSet()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *SessionUpsertBulk) SetStartedAt(v time.Time) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateStartedAt() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateStartedAt()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *SessionUpsertBulk) SetLastSeen(v time.Time) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateLastSeen() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateLastSeen()
	})
}

// SetRestoreRef sets the "restore_ref" field.
func (u *SessionUpsertBulk) SetRestoreRef(v []byte) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetRestoreRef(v)
	})
}

// UpdateRestoreRef sets the "restore_ref" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateRestoreRef() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateRestoreRef()
	})
}

// ClearRestoreRef clears the value of the "restore_ref" field.
func (u *SessionUpsertBulk) ClearRestoreRef() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.ClearRestoreRef()
	})
}

// Exec executes the query.
func (u *SessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
