// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twcclan/goback/index/sql/ent/archive"
	"github.com/twcclan/goback/index/sql/ent/predicate"
	"github.com/twcclan/goback/index/sql/ent/session"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *SessionUpdate) SetAgentID(v string) *SessionUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableAgentID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetBackupSet sets the "backup_set" field.
func (_u *SessionUpdate) SetBackupSet(v string) *SessionUpdate {
	_u.mutation.SetBackupSet(v)
	return _u
}

// SetNillableBackupSet sets the "backup_set" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableBackupSet(v *string) *SessionUpdate {
	if v != nil {
		_u.SetBackupSet(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SessionUpdate) SetStartedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableStartedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *SessionUpdate) SetLastSeen(v time.Time) *SessionUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLastSeen(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetRestoreRef sets the "restore_ref" field.
func (_u *SessionUpdate) SetRestoreRef(v []byte) *SessionUpdate {
	_u.mutation.SetRestoreRef(v)
	return _u
}

// ClearRestoreRef clears the value of the "restore_ref" field.
func (_u *SessionUpdate) ClearRestoreRef() *SessionUpdate {
	_u.mutation.ClearRestoreRef()
	return _u
}

// AddArchiveIDs adds the "archives" edge to the Archive entity by IDs.
func (_u *SessionUpdate) AddArchiveIDs(ids ...string) *SessionUpdate {
	_u.mutation.AddArchiveIDs(ids...)
	return _u
}

// AddArchives adds the "archives" edges to the Archive entity.
func (_u *SessionUpdate) AddArchives(v ...*Archive) *SessionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArchiveIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearArchives clears all "archives" edges to the Archive entity.
func (_u *SessionUpdate) ClearArchives() *SessionUpdate {
	_u.mutation.ClearArchives()
	return _u
}

// RemoveArchiveIDs removes the "archives" edge to Archive entities by IDs.
func (_u *SessionUpdate) RemoveArchiveIDs(ids ...string) *SessionUpdate {
	_u.mutation.RemoveArchiveIDs(ids...)
	return _u
}

// RemoveArchives removes "archives" edges to Archive entities.
func (_u *SessionUpdate) RemoveArchives(v ...*Archive) *SessionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArchiveIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(session.FieldAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackupSet(); ok {
		_spec.SetField(session.FieldBackupSet, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(session.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RestoreRef(); ok {
		_spec.SetField(session.FieldRestoreRef, field.TypeBytes, value)
	}
	if _u.mutation.RestoreRefCleared() {
		_spec.ClearField(session.FieldRestoreRef, field.TypeBytes)
	}
	if _u.mutation.ArchivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.ArchivesTable,
			Columns: []string{session.ArchivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArchivesIDs(); len(nodes) > 0 && !_u.mutation.ArchivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.ArchivesTable,
			Columns: []string{session.ArchivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.ArchivesTable,
			Columns: []string{session.ArchivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetAgentID sets the "agent_id" field.
func (_u *SessionUpdateOne) SetAgentID(v string) *SessionUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableAgentID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetBackupSet sets the "backup_set" field.
func (_u *SessionUpdateOne) SetBackupSet(v string) *SessionUpdateOne {
	_u.mutation.SetBackupSet(v)
	return _u
}

// SetNillableBackupSet sets the "backup_set" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableBackupSet(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetBackupSet(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SessionUpdateOne) SetStartedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableStartedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *SessionUpdateOne) SetLastSeen(v time.Time) *SessionUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLastSeen(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetRestoreRef sets the "restore_ref" field.
func (_u *SessionUpdateOne) SetRestoreRef(v []byte) *SessionUpdateOne {
	_u.mutation.SetRestoreRef(v)
	return _u
}

// ClearRestoreRef clears the value of the "restore_ref" field.
func (_u *SessionUpdateOne) ClearRestoreRef() *SessionUpdateOne {
	_u.mutation.ClearRestoreRef()
	return _u
}

// AddArchiveIDs adds the "archives" edge to the Archive entity by IDs.
func (_u *SessionUpdateOne) AddArchiveIDs(ids ...string) *SessionUpdateOne {
	_u.mutation.AddArchiveIDs(ids...)
	return _u
}

// AddArchives adds the "archives" edges to the Archive entity.
func (_u *SessionUpdateOne) AddArchives(v ...*Archive) *SessionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArchiveIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearArchives clears all "archives" edges to the Archive entity.
func (_u *SessionUpdateOne) ClearArchives() *SessionUpdateOne {
	_u.mutation.ClearArchives()
	return _u
}

// RemoveArchiveIDs removes the "archives" edge to Archive entities by IDs.
func (_u *SessionUpdateOne) RemoveArchiveIDs(ids ...string) *SessionUpdateOne {
	_u.mutation.RemoveArchiveIDs(ids...)
	return _u
}

// RemoveArchives removes "archives" edges to Archive entities.
func (_u *SessionUpdateOne) RemoveArchives(v ...*Archive) *SessionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArchiveIDs(ids...)
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(session.FieldAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackupSet(); ok {
		_spec.SetField(session.FieldBackupSet, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(session.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RestoreRef(); ok {
		_spec.SetField(session.FieldRestoreRef, field.TypeBytes, value)
	}
	if _u.mutation.RestoreRefCleared() {
		_spec.ClearField(session.FieldRestoreRef, field.TypeBytes)
	}
	if _u.mutation.ArchivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.ArchivesTable,
			Columns: []string{session.ArchivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArchivesIDs(); len(nodes) > 0 && !_u.mutation.ArchivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.ArchivesTable,
			Columns: []string{session.ArchivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArchivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.ArchivesTable,
			Columns: []string{session.ArchivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
