// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/twcclan/goback/index/sql/ent/set"
)

// Set is the model entity for the Set schema.
type Set struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// State holds the value of the "state" field.
	State set.State `json:"state,omitempty"`
	// RetentionPolicy holds the value of the "retention_policy" field.
	RetentionPolicy *string `json:"retention_policy,omitempty"`
	// RetentionPaused holds the value of the "retention_paused" field.
	RetentionPaused bool `json:"retention_paused,omitempty"`
	// Erase holds the value of the "erase" field.
	Erase bool `json:"erase,omitempty"`
	// Rescan holds the value of the "rescan" field.
	Rescan bool `json:"rescan,omitempty"`
	// PhysicalSize holds the value of the "physical_size" field.
	PhysicalSize *int64 `json:"physical_size,omitempty"`
	// DeduplicatedSize holds the value of the "deduplicated_size" field.
	DeduplicatedSize *int64 `json:"deduplicated_size,omitempty"`
	// AloneSize holds the value of the "alone_size" field.
	AloneSize *int64 `json:"alone_size,omitempty"`
	// ExclusiveSize holds the value of the "exclusive_size" field.
	ExclusiveSize *int64 `json:"exclusive_size,omitempty"`
	// DeduplicatedAloneSize holds the value of the "deduplicated_alone_size" field.
	DeduplicatedAloneSize *int64 `json:"deduplicated_alone_size,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SetQuery when eager-loading is set.
	Edges        SetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SetEdges holds the relations/edges for other nodes in the graph.
type SetEdges struct {
	// Files holds the value of the files edge.
	Files []*File `json:"files,omitempty"`
	// Trees holds the value of the trees edge.
	Trees []*Tree `json:"trees,omitempty"`
	// Refs holds the value of the refs edge.
	Refs []*SetRef `json:"refs,omitempty"`
	// Damaged holds the value of the damaged edge.
	Damaged []*DamagedPath `json:"damaged,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// FilesOrErr returns the Files value or an error if the edge
// was not loaded in eager-loading.
func (e SetEdges) FilesOrErr() ([]*File, error) {
	if e.loadedTypes[0] {
		return e.Files, nil
	}
	return nil, &NotLoadedError{edge: "files"}
}

// TreesOrErr returns the Trees value or an error if the edge
// was not loaded in eager-loading.
func (e SetEdges) TreesOrErr() ([]*Tree, error) {
	if e.loadedTypes[1] {
		return e.Trees, nil
	}
	return nil, &NotLoadedError{edge: "trees"}
}

// RefsOrErr returns the Refs value or an error if the edge
// was not loaded in eager-loading.
func (e SetEdges) RefsOrErr() ([]*SetRef, error) {
	if e.loadedTypes[2] {
		return e.Refs, nil
	}
	return nil, &NotLoadedError{edge: "refs"}
}

// DamagedOrErr returns the Damaged value or an error if the edge
// was not loaded in eager-loading.
func (e SetEdges) DamagedOrErr() ([]*DamagedPath, error) {
	if e.loadedTypes[3] {
		return e.Damaged, nil
	}
	return nil, &NotLoadedError{edge: "damaged"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Set) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case set.FieldRetentionPaused, set.FieldErase, set.FieldRescan:
			values[i] = new(sql.NullBool)
		case set.FieldID, set.FieldPhysicalSize, set.FieldDeduplicatedSize, set.FieldAloneSize, set.FieldExclusiveSize, set.FieldDeduplicatedAloneSize:
			values[i] = new(sql.NullInt64)
		case set.FieldName, set.FieldState, set.FieldRetentionPolicy:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Set fields.
func (_m *Set) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case set.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case set.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case set.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = set.State(value.String)
			}
		case set.FieldRetentionPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field retention_policy", values[i])
			} else if value.Valid {
				_m.RetentionPolicy = new(string)
				*_m.RetentionPolicy = value.String
			}
		case set.FieldRetentionPaused:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field retention_paused", values[i])
			} else if value.Valid {
				_m.RetentionPaused = value.Bool
			}
		case set.FieldErase:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field erase", values[i])
			} else if value.Valid {
				_m.Erase = value.Bool
			}
		case set.FieldRescan:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field rescan", values[i])
			} else if value.Valid {
				_m.Rescan = value.Bool
			}
		case set.FieldPhysicalSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field physical_size", values[i])
			} else if value.Valid {
				_m.PhysicalSize = new(int64)
				*_m.PhysicalSize = value.Int64
			}
		case set.FieldDeduplicatedSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deduplicated_size", values[i])
			} else if value.Valid {
				_m.DeduplicatedSize = new(int64)
				*_m.DeduplicatedSize = value.Int64
			}
		case set.FieldAloneSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field alone_size", values[i])
			} else if value.Valid {
				_m.AloneSize = new(int64)
				*_m.AloneSize = value.Int64
			}
		case set.FieldExclusiveSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exclusive_size", values[i])
			} else if value.Valid {
				_m.ExclusiveSize = new(int64)
				*_m.ExclusiveSize = value.Int64
			}
		case set.FieldDeduplicatedAloneSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deduplicated_alone_size", values[i])
			} else if value.Valid {
				_m.DeduplicatedAloneSize = new(int64)
				*_m.DeduplicatedAloneSize = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Set.
// This includes values selected through modifiers, order, etc.
func (_m *Set) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFiles queries the "files" edge of the Set entity.
func (_m *Set) QueryFiles() *FileQuery {
	return NewSetClient(_m.config).QueryFiles(_m)
}

// QueryTrees queries the "trees" edge of the Set entity.
func (_m *Set) QueryTrees() *TreeQuery {
	return NewSetClient(_m.config).QueryTrees(_m)
}

// QueryRefs queries the "refs" edge of the Set entity.
func (_m *Set) QueryRefs() *SetRefQuery {
	return NewSetClient(_m.config).QueryRefs(_m)
}

// QueryDamaged queries the "damaged" edge of the Set entity.
func (_m *Set) QueryDamaged() *DamagedPathQuery {
	return NewSetClient(_m.config).QueryDamaged(_m)
}

// Update returns a builder for updating this Set.
// Note that you need to call Set.Unwrap() before calling this method if this Set
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Set) Update() *SetUpdateOne {
	return NewSetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Set entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Set) Unwrap() *Set {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Set is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Set) String() string {
	var builder strings.Builder
	builder.WriteString("Set(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	if v := _m.RetentionPolicy; v != nil {
		builder.WriteString("retention_policy=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("retention_paused=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetentionPaused))
	builder.WriteString(", ")
	builder.WriteString("erase=")
	builder.WriteString(fmt.Sprintf("%v", _m.Erase))
	builder.WriteString(", ")
	builder.WriteString("rescan=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rescan))
	builder.WriteString(", ")
	if v := _m.PhysicalSize; v != nil {
		builder.WriteString("physical_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeduplicatedSize; v != nil {
		builder.WriteString("deduplicated_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AloneSize; v != nil {
		builder.WriteString("alone_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExclusiveSize; v != nil {
		builder.WriteString("exclusive_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeduplicatedAloneSize; v != nil {
		builder.WriteString("deduplicated_alone_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Sets is a parsable slice of Set.
type Sets []*Set
