// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twcclan/goback/index/sql/ent/damagedpath"
	"github.com/twcclan/goback/index/sql/ent/file"
	"github.com/twcclan/goback/index/sql/ent/set"
	"github.com/twcclan/goback/index/sql/ent/setref"
	"github.com/twcclan/goback/index/sql/ent/tree"
)

// SetCreate is the builder for creating a Set entity.
type SetCreate struct {
	config
	mutation *SetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *SetCreate) SetName(v string) *SetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *SetCreate) SetAgentID(v string) *SetCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *SetCreate) SetNillableAgentID(v *string) *SetCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *SetCreate) SetState(v set.State) *SetCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *SetCreate) SetNillableState(v *set.State) *SetCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetRetentionPolicy sets the "retention_policy" field.
func (_c *SetCreate) SetRetentionPolicy(v string) *SetCreate {
	_c.mutation.SetRetentionPolicy(v)
	return _c
}

// SetNillableRetentionPolicy sets the "retention_policy" field if the given value is not nil.
func (_c *SetCreate) SetNillableRetentionPolicy(v *string) *SetCreate {
	if v != nil {
		_c.SetRetentionPolicy(*v)
	}
	return _c
}

// SetRetentionPaused sets the "retention_paused" field.
func (_c *SetCreate) SetRetentionPaused(v bool) *SetCreate {
	_c.mutation.SetRetentionPaused(v)
	return _c
}

// SetNillableRetentionPaused sets the "retention_paused" field if the given value is not nil.
func (_c *SetCreate) SetNillableRetentionPaused(v *bool) *SetCreate {
	if v != nil {
		_c.SetRetentionPaused(*v)
	}
	return _c
}

// SetErase sets the "erase" field.
func (_c *SetCreate) SetErase(v bool) *SetCreate {
	_c.mutation.SetErase(v)
	return _c
}

// SetNillableErase sets the "erase" field if the given value is not nil.
func (_c *SetCreate) SetNillableErase(v *bool) *SetCreate {
	if v != nil {
		_c.SetErase(*v)
	}
	return _c
}

// SetRescan sets the "rescan" field.
func (_c *SetCreate) SetRescan(v bool) *SetCreate {
	_c.mutation.SetRescan(v)
	return _c
}

// SetNillableRescan sets the "rescan" field if the given value is not nil.
func (_c *SetCreate) SetNillableRescan(v *bool) *SetCreate {
	if v != nil {
		_c.SetRescan(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SetCreate) SetID(v int64) *SetCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_c *SetCreate) AddFileIDs(ids ...int) *SetCreate {
	_c.mutation.AddFileIDs(ids...)
	return _c
}

// AddFiles adds the "files" edges to the File entity.
func (_c *SetCreate) AddFiles(v ...*File) *SetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFileIDs(ids...)
}

// AddTreeIDs adds the "trees" edge to the Tree entity by IDs.
func (_c *SetCreate) AddTreeIDs(ids ...int) *SetCreate {
	_c.mutation.AddTreeIDs(ids...)
	return _c
}

// AddTrees adds the "trees" edges to the Tree entity.
func (_c *SetCreate) AddTrees(v ...*Tree) *SetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTreeIDs(ids...)
}

// AddRefIDs adds the "refs" edge to the SetRef entity by IDs.
func (_c *SetCreate) AddRefIDs(ids ...int) *SetCreate {
	_c.mutation.AddRefIDs(ids...)
	return _c
}

// AddRefs adds the "refs" edges to the SetRef entity.
func (_c *SetCreate) AddRefs(v ...*SetRef) *SetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRefIDs(ids...)
}

// AddDamagedIDs adds the "damaged" edge to the DamagedPath entity by IDs.
func (_c *SetCreate) AddDamagedIDs(ids ...int) *SetCreate {
	_c.mutation.AddDamagedIDs(ids...)
	return _c
}

// AddDamaged adds the "damaged" edges to the DamagedPath entity.
func (_c *SetCreate) AddDamaged(v ...*DamagedPath) *SetCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDamagedIDs(ids...)
}

// Mutation returns the SetMutation object of the builder.
func (_c *SetCreate) Mutation() *SetMutation {
	return _c.mutation
}

// Save creates the Set in the database.
func (_c *SetCreate) Save(ctx context.Context) (*Set, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SetCreate) SaveX(ctx context.Context) *Set {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SetCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := set.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.RetentionPaused(); !ok {
		v := set.DefaultRetentionPaused
		_c.mutation.SetRetentionPaused(v)
	}
	if _, ok := _c.mutation.Erase(); !ok {
		v := set.DefaultErase
		_c.mutation.SetErase(v)
	}
	if _, ok := _c.mutation.Rescan(); !ok {
		v := set.DefaultRescan
		_c.mutation.SetRescan(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SetCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Set.name"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Set.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := set.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Set.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetentionPaused(); !ok {
		return &ValidationError{Name: "retention_paused", err: errors.New(`ent: missing required field "Set.retention_paused"`)}
	}
	if _, ok := _c.mutation.Erase(); !ok {
		return &ValidationError{Name: "erase", err: errors.New(`ent: missing required field "Set.erase"`)}
	}
	if _, ok := _c.mutation.Rescan(); !ok {
		return &ValidationError{Name: "rescan", err: errors.New(`ent: missing required field "Set.rescan"`)}
	}
	return nil
}

func (_c *SetCreate) sqlSave(ctx context.Context) (*Set, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SetCreate) createSpec() (*Set, *sqlgraph.CreateSpec) {
	var (
		_node = &Set{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(set.Table, sqlgraph.NewFieldSpec(set.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(set.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(set.FieldAgentID, field.TypeString, value)
		_node.AgentID = &value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(set.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.RetentionPolicy(); ok {
		_spec.SetField(set.FieldRetentionPolicy, field.TypeString, value)
		_node.RetentionPolicy = &value
	}
	if value, ok := _c.mutation.RetentionPaused(); ok {
		_spec.SetField(set.FieldRetentionPaused, field.TypeBool, value)
		_node.RetentionPaused = value
	}
	if value, ok := _c.mutation.Erase(); ok {
		_spec.SetField(set.FieldErase, field.TypeBool, value)
		_node.Erase = value
	}
	if value, ok := _c.mutation.Rescan(); ok {
		_spec.SetField(set.FieldRescan, field.TypeBool, value)
		_node.Rescan = value
	}
	if nodes := _c.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   set.FilesTable,
			Columns: []string{set.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TreesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   set.TreesTable,
			Columns: []string{set.TreesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tree.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   set.RefsTable,
			Columns: []string{set.RefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(setref.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DamagedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   set.DamagedTable,
			Columns: []string{set.DamagedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(damagedpath.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Set.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SetUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SetCreate) OnConflict(opts ...sql.ConflictOption) *SetUpsertOne {
	_c.conflict = opts
	return &SetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Set.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SetCreate) OnConflictColumns(columns ...string) *SetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SetUpsertOne{
		create: _c,
	}
}

type (
	// SetUpsertOne is the builder for "upsert"-ing
	//  one Set node.
	SetUpsertOne struct {
		create *SetCreate
	}

	// SetUpsert is the "OnConflict" setter.
	SetUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SetUpsert) SetName(v string) *SetUpsert {
	u.Set(set.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SetUpsert) UpdateName() *SetUpsert {
	u.SetExcluded(set.FieldName)
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *SetUpsert) SetAgentID(v string) *SetUpsert {
	u.Set(set.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *SetUpsert) UpdateAgentID() *SetUpsert {
	u.SetExcluded(set.FieldAgentID)
	return u
}

// ClearAgentID clears the value of the "agent_id" field.
func (u *SetUpsert) ClearAgentID() *SetUpsert {
	u.SetNull(set.FieldAgentID)
	return u
}

// SetState sets the "state" field.
func (u *SetUpsert) SetState(v set.State) *SetUpsert {
	u.Set(set.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *SetUpsert) UpdateState() *SetUpsert {
	u.SetExcluded(set.FieldState)
	return u
}

// SetRetentionPolicy sets the "retention_policy" field.
func (u *SetUpsert) SetRetentionPolicy(v string) *SetUpsert {
	u.Set(set.FieldRetentionPolicy, v)
	return u
}

// UpdateRetentionPolicy sets the "retention_policy" field to the value that was provided on create.
func (u *SetUpsert) UpdateRetentionPolicy() *SetUpsert {
	u.SetExcluded(set.FieldRetentionPolicy)
	return u
}

// ClearRetentionPolicy clears the value of the "retention_policy" field.
func (u *SetUpsert) ClearRetentionPolicy() *SetUpsert {
	u.SetNull(set.FieldRetentionPolicy)
	return u
}

// SetRetentionPaused sets the "retention_paused" field.
func (u *SetUpsert) SetRetentionPaused(v bool) *SetUpsert {
	u.Set(set.FieldRetentionPaused, v)
	return u
}

// UpdateRetentionPaused sets the "retention_paused" field to the value that was provided on create.
func (u *SetUpsert) UpdateRetentionPaused() *SetUpsert {
	u.SetExcluded(set.FieldRetentionPaused)
	return u
}

// SetErase sets the "erase" field.
func (u *SetUpsert) SetErase(v bool) *SetUpsert {
	u.Set(set.FieldErase, v)
	return u
}

// UpdateErase sets the "erase" field to the value that was provided on create.
func (u *SetUpsert) UpdateErase() *SetUpsert {
	u.SetExcluded(set.FieldErase)
	return u
}

// SetRescan sets the "rescan" field.
func (u *SetUpsert) SetRescan(v bool) *SetUpsert {
	u.Set(set.FieldRescan, v)
	return u
}

// UpdateRescan sets the "rescan" field to the value that was provided on create.
func (u *SetUpsert) UpdateRescan() *SetUpsert {
	u.SetExcluded(set.FieldRescan)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Set.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(set.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SetUpsertOne) UpdateNewValues() *SetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(set.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Set.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SetUpsertOne) Ignore() *SetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SetUpsertOne) DoNothing() *SetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SetCreate.OnConflict
// documentation for more info.
func (u *SetUpsertOne) Update(set func(*SetUpsert)) *SetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SetUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SetUpsertOne) SetName(v string) *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SetUpsertOne) UpdateName() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.UpdateName()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *SetUpsertOne) SetAgentID(v string) *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *SetUpsertOne) UpdateAgentID() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.UpdateAgentID()
	})
}

// ClearAgentID clears the value of the "agent_id" field.
func (u *SetUpsertOne) ClearAgentID() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.ClearAgentID()
	})
}

// SetState sets the "state" field.
func (u *SetUpsertOne) SetState(v set.State) *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *SetUpsertOne) UpdateState() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.UpdateState()
	})
}

// SetRetentionPolicy sets the "retention_policy" field.
func (u *SetUpsertOne) SetRetentionPolicy(v string) *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.SetRetentionPolicy(v)
	})
}

// UpdateRetentionPolicy sets the "retention_policy" field to the value that was provided on create.
func (u *SetUpsertOne) UpdateRetentionPolicy() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.UpdateRetentionPolicy()
	})
}

// ClearRetentionPolicy clears the value of the "retention_policy" field.
func (u *SetUpsertOne) ClearRetentionPolicy() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.ClearRetentionPolicy()
	})
}

// SetRetentionPaused sets the "retention_paused" field.
func (u *SetUpsertOne) SetRetentionPaused(v bool) *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.SetRetentionPaused(v)
	})
}

// UpdateRetentionPaused sets the "retention_paused" field to the value that was provided on create.
func (u *SetUpsertOne) UpdateRetentionPaused() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.UpdateRetentionPaused()
	})
}

// SetErase sets the "erase" field.
func (u *SetUpsertOne) SetErase(v bool) *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.SetErase(v)
	})
}

// UpdateErase sets the "erase" field to the value that was provided on create.
func (u *SetUpsertOne) UpdateErase() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.UpdateErase()
	})
}

// SetRescan sets the "rescan" field.
func (u *SetUpsertOne) SetRescan(v bool) *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.SetRescan(v)
	})
}

// UpdateRescan sets the "rescan" field to the value that was provided on create.
func (u *SetUpsertOne) UpdateRescan() *SetUpsertOne {
	return u.Update(func(s *SetUpsert) {
		s.UpdateRescan()
	})
}

// Exec executes the query.
func (u *SetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SetUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SetUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SetCreateBulk is the builder for creating many Set entities in bulk.
type SetCreateBulk struct {
	config
	err      error
	builders []*SetCreate
	conflict []sql.ConflictOption
}

// Save creates the Set entities in the database.
func (_c *SetCreateBulk) Save(ctx context.Context) ([]*Set, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Set, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SetCreateBulk) SaveX(ctx context.Context) []*Set {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Set.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SetUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SetCreateBulk) OnConflict(opts ...sql.ConflictOption) *SetUpsertBulk {
	_c.conflict = opts
	return &SetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Set.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SetCreateBulk) OnConflictColumns(columns ...string) *SetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SetUpsertBulk{
		create: _c,
	}
}

// SetUpsertBulk is the builder for "upsert"-ing
// a bulk of Set nodes.
type SetUpsertBulk struct {
	create *SetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Set.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(set.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SetUpsertBulk) UpdateNewValues() *SetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(set.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Set.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SetUpsertBulk) Ignore() *SetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SetUpsertBulk) DoNothing() *SetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SetCreateBulk.OnConflict
// documentation for more info.
func (u *SetUpsertBulk) Update(set func(*SetUpsert)) *SetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SetUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SetUpsertBulk) SetName(v string) *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SetUpsertBulk) UpdateName() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.UpdateName()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *SetUpsertBulk) SetAgentID(v string) *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *SetUpsertBulk) UpdateAgentID() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.UpdateAgentID()
	})
}

// ClearAgentID clears the value of the "agent_id" field.
func (u *SetUpsertBulk) ClearAgentID() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.ClearAgentID()
	})
}

// SetState sets the "state" field.
func (u *SetUpsertBulk) SetState(v set.State) *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *SetUpsertBulk) UpdateState() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.UpdateState()
	})
}

// SetRetentionPolicy sets the "retention_policy" field.
func (u *SetUpsertBulk) SetRetentionPolicy(v string) *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.SetRetentionPolicy(v)
	})
}

// UpdateRetentionPolicy sets the "retention_policy" field to the value that was provided on create.
func (u *SetUpsertBulk) UpdateRetentionPolicy() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.UpdateRetentionPolicy()
	})
}

// ClearRetentionPolicy clears the value of the "retention_policy" field.
func (u *SetUpsertBulk) ClearRetentionPolicy() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.ClearRetentionPolicy()
	})
}

// SetRetentionPaused sets the "retention_paused" field.
func (u *SetUpsertBulk) SetRetentionPaused(v bool) *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.SetRetentionPaused(v)
	})
}

// UpdateRetentionPaused sets the "retention_paused" field to the value that was provided on create.
func (u *SetUpsertBulk) UpdateRetentionPaused() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.UpdateRetentionPaused()
	})
}

// SetErase sets the "erase" field.
func (u *SetUpsertBulk) SetErase(v bool) *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.SetErase(v)
	})
}

// UpdateErase sets the "erase" field to the value that was provided on create.
func (u *SetUpsertBulk) UpdateErase() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.UpdateErase()
	})
}

// SetRescan sets the "rescan" field.
func (u *SetUpsertBulk) SetRescan(v bool) *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.SetRescan(v)
	})
}

// UpdateRescan sets the "rescan" field to the value that was provided on create.
func (u *SetUpsertBulk) UpdateRescan() *SetUpsertBulk {
	return u.Update(func(s *SetUpsert) {
		s.UpdateRescan()
	})
}

// Exec executes the query.
func (u *SetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
