// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/twcclan/goback/index/sql/ent/set"
	"github.com/twcclan/goback/index/sql/ent/setref"
)

// SetRefCreate is the builder for creating a SetRef entity.
type SetRefCreate struct {
	config
	mutation *SetRefMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSetID sets the "set_id" field.
func (_c *SetRefCreate) SetSetID(v int64) *SetRefCreate {
	_c.mutation.SetSetID(v)
	return _c
}

// SetRef sets the "ref" field.
func (_c *SetRefCreate) SetRef(v []byte) *SetRefCreate {
	_c.mutation.SetRef(v)
	return _c
}

// SetSet sets the "set" edge to the Set entity.
func (_c *SetRefCreate) SetSet(v *Set) *SetRefCreate {
	return _c.SetSetID(v.ID)
}

// Mutation returns the SetRefMutation object of the builder.
func (_c *SetRefCreate) Mutation() *SetRefMutation {
	return _c.mutation
}

// Save creates the SetRef in the database.
func (_c *SetRefCreate) Save(ctx context.Context) (*SetRef, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SetRefCreate) SaveX(ctx context.Context) *SetRef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SetRefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SetRefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SetRefCreate) check() error {
	if _, ok := _c.mutation.SetID(); !ok {
		return &ValidationError{Name: "set_id", err: errors.New(`ent: missing required field "SetRef.set_id"`)}
	}
	if _, ok := _c.mutation.Ref(); !ok {
		return &ValidationError{Name: "ref", err: errors.New(`ent: missing required field "SetRef.ref"`)}
	}
	if len(_c.mutation.SetIDs()) == 0 {
		return &ValidationError{Name: "set", err: errors.New(`ent: missing required edge "SetRef.set"`)}
	}
	return nil
}

func (_c *SetRefCreate) sqlSave(ctx context.Context) (*SetRef, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SetRefCreate) createSpec() (*SetRef, *sqlgraph.CreateSpec) {
	var (
		_node = &SetRef{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(setref.Table, sqlgraph.NewFieldSpec(setref.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Ref(); ok {
		_spec.SetField(setref.FieldRef, field.TypeBytes, value)
		_node.Ref = value
	}
	if nodes := _c.mutation.SetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   setref.SetTable,
			Columns: []string{setref.SetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(set.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SetRef.Create().
//		SetSetID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SetRefUpsert) {
//			SetSetID(v+v).
//		}).
//		Exec(ctx)
func (_c *SetRefCreate) OnConflict(opts ...sql.ConflictOption) *SetRefUpsertOne {
	_c.conflict = opts
	return &SetRefUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SetRef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SetRefCreate) OnConflictColumns(columns ...string) *SetRefUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SetRefUpsertOne{
		create: _c,
	}
}

type (
	// SetRefUpsertOne is the builder for "upsert"-ing
	//  one SetRef node.
	SetRefUpsertOne struct {
		create *SetRefCreate
	}

	// SetRefUpsert is the "OnConflict" setter.
	SetRefUpsert struct {
		*sql.UpdateSet
	}
)

// SetSetID sets the "set_id" field.
func (u *SetRefUpsert) SetSetID(v int64) *SetRefUpsert {
	u.Set(setref.FieldSetID, v)
	return u
}

// UpdateSetID sets the "set_id" field to the value that was provided on create.
func (u *SetRefUpsert) UpdateSetID() *SetRefUpsert {
	u.SetExcluded(setref.FieldSetID)
	return u
}

// SetRef sets the "ref" field.
func (u *SetRefUpsert) SetRef(v []byte) *SetRefUpsert {
	u.Set(setref.FieldRef, v)
	return u
}

// UpdateRef sets the "ref" field to the value that was provided on create.
func (u *SetRefUpsert) UpdateRef() *SetRefUpsert {
	u.SetExcluded(setref.FieldRef)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SetRef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SetRefUpsertOne) UpdateNewValues() *SetRefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SetRef.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SetRefUpsertOne) Ignore() *SetRefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SetRefUpsertOne) DoNothing() *SetRefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SetRefCreate.OnConflict
// documentation for more info.
func (u *SetRefUpsertOne) Update(set func(*SetRefUpsert)) *SetRefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SetRefUpsert{UpdateSet: update})
	}))
	return u
}

// SetSetID sets the "set_id" field.
func (u *SetRefUpsertOne) SetSetID(v int64) *SetRefUpsertOne {
	return u.Update(func(s *SetRefUpsert) {
		s.SetSetID(v)
	})
}

// UpdateSetID sets the "set_id" field to the value that was provided on create.
func (u *SetRefUpsertOne) UpdateSetID() *SetRefUpsertOne {
	return u.Update(func(s *SetRefUpsert) {
		s.UpdateSetID()
	})
}

// SetRef sets the "ref" field.
func (u *SetRefUpsertOne) SetRef(v []byte) *SetRefUpsertOne {
	return u.Update(func(s *SetRefUpsert) {
		s.SetRef(v)
	})
}

// UpdateRef sets the "ref" field to the value that was provided on create.
func (u *SetRefUpsertOne) UpdateRef() *SetRefUpsertOne {
	return u.Update(func(s *SetRefUpsert) {
		s.UpdateRef()
	})
}

// Exec executes the query.
func (u *SetRefUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SetRefCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SetRefUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SetRefUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SetRefUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SetRefCreateBulk is the builder for creating many SetRef entities in bulk.
type SetRefCreateBulk struct {
	config
	err      error
	builders []*SetRefCreate
	conflict []sql.ConflictOption
}

// Save creates the SetRef entities in the database.
func (_c *SetRefCreateBulk) Save(ctx context.Context) ([]*SetRef, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SetRef, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SetRefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SetRefCreateBulk) SaveX(ctx context.Context) []*SetRef {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SetRefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SetRefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SetRef.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SetRefUpsert) {
//			SetSetID(v+v).
//		}).
//		Exec(ctx)
func (_c *SetRefCreateBulk) OnConflict(opts ...sql.ConflictOption) *SetRefUpsertBulk {
	_c.conflict = opts
	return &SetRefUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SetRef.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SetRefCreateBulk) OnConflictColumns(columns ...string) *SetRefUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SetRefUpsertBulk{
		create: _c,
	}
}

// SetRefUpsertBulk is the builder for "upsert"-ing
// a bulk of SetRef nodes.
type SetRefUpsertBulk struct {
	create *SetRefCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SetRef.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SetRefUpsertBulk) UpdateNewValues() *SetRefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SetRef.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SetRefUpsertBulk) Ignore() *SetRefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SetRefUpsertBulk) DoNothing() *SetRefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SetRefCreateBulk.OnConflict
// documentation for more info.
func (u *SetRefUpsertBulk) Update(set func(*SetRefUpsert)) *SetRefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SetRefUpsert{UpdateSet: update})
	}))
	return u
}

// SetSetID sets the "set_id" field.
func (u *SetRefUpsertBulk) SetSetID(v int64) *SetRefUpsertBulk {
	return u.Update(func(s *SetRefUpsert) {
		s.SetSetID(v)
	})
}

// UpdateSetID sets the "set_id" field to the value that was provided on create.
func (u *SetRefUpsertBulk) UpdateSetID() *SetRefUpsertBulk {
	return u.Update(func(s *SetRefUpsert) {
		s.UpdateSetID()
	})
}

// SetRef sets the "ref" field.
func (u *SetRefUpsertBulk) SetRef(v []byte) *SetRefUpsertBulk {
	return u.Update(func(s *SetRefUpsert) {
		s.SetRef(v)
	})
}

// UpdateRef sets the "ref" field to the value that was provided on create.
func (u *SetRefUpsertBulk) UpdateRef() *SetRefUpsertBulk {
	return u.Update(func(s *SetRefUpsert) {
		s.UpdateRef()
	})
}

// Exec executes the query.
func (u *SetRefUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SetRefCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SetRefCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SetRefUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
