// Code generated by ent, DO NOT EDIT.

package object

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/twcclan/goback/index/sql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Object {
	return predicate.Object(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Object {
	return predicate.Object(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Object {
	return predicate.Object(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Object {
	return predicate.Object(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Object {
	return predicate.Object(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Object {
	return predicate.Object(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Object {
	return predicate.Object(sql.FieldLTE(FieldID, id))
}

// Ref applies equality check predicate on the "ref" field. It's identical to RefEQ.
func Ref(v []byte) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldRef, v))
}

// ArchiveID applies equality check predicate on the "archive_id" field. It's identical to ArchiveIDEQ.
func ArchiveID(v string) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldArchiveID, v))
}

// Start applies equality check predicate on the "start" field. It's identical to StartEQ.
func Start(v uint32) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldStart, v))
}

// Length applies equality check predicate on the "length" field. It's identical to LengthEQ.
func Length(v uint32) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldLength, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v uint32) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldType, v))
}

// RefEQ applies the EQ predicate on the "ref" field.
func RefEQ(v []byte) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldRef, v))
}

// RefNEQ applies the NEQ predicate on the "ref" field.
func RefNEQ(v []byte) predicate.Object {
	return predicate.Object(sql.FieldNEQ(FieldRef, v))
}

// RefIn applies the In predicate on the "ref" field.
func RefIn(vs ...[]byte) predicate.Object {
	return predicate.Object(sql.FieldIn(FieldRef, vs...))
}

// RefNotIn applies the NotIn predicate on the "ref" field.
func RefNotIn(vs ...[]byte) predicate.Object {
	return predicate.Object(sql.FieldNotIn(FieldRef, vs...))
}

// RefGT applies the GT predicate on the "ref" field.
func RefGT(v []byte) predicate.Object {
	return predicate.Object(sql.FieldGT(FieldRef, v))
}

// RefGTE applies the GTE predicate on the "ref" field.
func RefGTE(v []byte) predicate.Object {
	return predicate.Object(sql.FieldGTE(FieldRef, v))
}

// RefLT applies the LT predicate on the "ref" field.
func RefLT(v []byte) predicate.Object {
	return predicate.Object(sql.FieldLT(FieldRef, v))
}

// RefLTE applies the LTE predicate on the "ref" field.
func RefLTE(v []byte) predicate.Object {
	return predicate.Object(sql.FieldLTE(FieldRef, v))
}

// ArchiveIDEQ applies the EQ predicate on the "archive_id" field.
func ArchiveIDEQ(v string) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldArchiveID, v))
}

// ArchiveIDNEQ applies the NEQ predicate on the "archive_id" field.
func ArchiveIDNEQ(v string) predicate.Object {
	return predicate.Object(sql.FieldNEQ(FieldArchiveID, v))
}

// ArchiveIDIn applies the In predicate on the "archive_id" field.
func ArchiveIDIn(vs ...string) predicate.Object {
	return predicate.Object(sql.FieldIn(FieldArchiveID, vs...))
}

// ArchiveIDNotIn applies the NotIn predicate on the "archive_id" field.
func ArchiveIDNotIn(vs ...string) predicate.Object {
	return predicate.Object(sql.FieldNotIn(FieldArchiveID, vs...))
}

// ArchiveIDGT applies the GT predicate on the "archive_id" field.
func ArchiveIDGT(v string) predicate.Object {
	return predicate.Object(sql.FieldGT(FieldArchiveID, v))
}

// ArchiveIDGTE applies the GTE predicate on the "archive_id" field.
func ArchiveIDGTE(v string) predicate.Object {
	return predicate.Object(sql.FieldGTE(FieldArchiveID, v))
}

// ArchiveIDLT applies the LT predicate on the "archive_id" field.
func ArchiveIDLT(v string) predicate.Object {
	return predicate.Object(sql.FieldLT(FieldArchiveID, v))
}

// ArchiveIDLTE applies the LTE predicate on the "archive_id" field.
func ArchiveIDLTE(v string) predicate.Object {
	return predicate.Object(sql.FieldLTE(FieldArchiveID, v))
}

// ArchiveIDContains applies the Contains predicate on the "archive_id" field.
func ArchiveIDContains(v string) predicate.Object {
	return predicate.Object(sql.FieldContains(FieldArchiveID, v))
}

// ArchiveIDHasPrefix applies the HasPrefix predicate on the "archive_id" field.
func ArchiveIDHasPrefix(v string) predicate.Object {
	return predicate.Object(sql.FieldHasPrefix(FieldArchiveID, v))
}

// ArchiveIDHasSuffix applies the HasSuffix predicate on the "archive_id" field.
func ArchiveIDHasSuffix(v string) predicate.Object {
	return predicate.Object(sql.FieldHasSuffix(FieldArchiveID, v))
}

// ArchiveIDEqualFold applies the EqualFold predicate on the "archive_id" field.
func ArchiveIDEqualFold(v string) predicate.Object {
	return predicate.Object(sql.FieldEqualFold(FieldArchiveID, v))
}

// ArchiveIDContainsFold applies the ContainsFold predicate on the "archive_id" field.
func ArchiveIDContainsFold(v string) predicate.Object {
	return predicate.Object(sql.FieldContainsFold(FieldArchiveID, v))
}

// StartEQ applies the EQ predicate on the "start" field.
func StartEQ(v uint32) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldStart, v))
}

// StartNEQ applies the NEQ predicate on the "start" field.
func StartNEQ(v uint32) predicate.Object {
	return predicate.Object(sql.FieldNEQ(FieldStart, v))
}

// StartIn applies the In predicate on the "start" field.
func StartIn(vs ...uint32) predicate.Object {
	return predicate.Object(sql.FieldIn(FieldStart, vs...))
}

// StartNotIn applies the NotIn predicate on the "start" field.
func StartNotIn(vs ...uint32) predicate.Object {
	return predicate.Object(sql.FieldNotIn(FieldStart, vs...))
}

// StartGT applies the GT predicate on the "start" field.
func StartGT(v uint32) predicate.Object {
	return predicate.Object(sql.FieldGT(FieldStart, v))
}

// StartGTE applies the GTE predicate on the "start" field.
func StartGTE(v uint32) predicate.Object {
	return predicate.Object(sql.FieldGTE(FieldStart, v))
}

// StartLT applies the LT predicate on the "start" field.
func StartLT(v uint32) predicate.Object {
	return predicate.Object(sql.FieldLT(FieldStart, v))
}

// StartLTE applies the LTE predicate on the "start" field.
func StartLTE(v uint32) predicate.Object {
	return predicate.Object(sql.FieldLTE(FieldStart, v))
}

// LengthEQ applies the EQ predicate on the "length" field.
func LengthEQ(v uint32) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldLength, v))
}

// LengthNEQ applies the NEQ predicate on the "length" field.
func LengthNEQ(v uint32) predicate.Object {
	return predicate.Object(sql.FieldNEQ(FieldLength, v))
}

// LengthIn applies the In predicate on the "length" field.
func LengthIn(vs ...uint32) predicate.Object {
	return predicate.Object(sql.FieldIn(FieldLength, vs...))
}

// LengthNotIn applies the NotIn predicate on the "length" field.
func LengthNotIn(vs ...uint32) predicate.Object {
	return predicate.Object(sql.FieldNotIn(FieldLength, vs...))
}

// LengthGT applies the GT predicate on the "length" field.
func LengthGT(v uint32) predicate.Object {
	return predicate.Object(sql.FieldGT(FieldLength, v))
}

// LengthGTE applies the GTE predicate on the "length" field.
func LengthGTE(v uint32) predicate.Object {
	return predicate.Object(sql.FieldGTE(FieldLength, v))
}

// LengthLT applies the LT predicate on the "length" field.
func LengthLT(v uint32) predicate.Object {
	return predicate.Object(sql.FieldLT(FieldLength, v))
}

// LengthLTE applies the LTE predicate on the "length" field.
func LengthLTE(v uint32) predicate.Object {
	return predicate.Object(sql.FieldLTE(FieldLength, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v uint32) predicate.Object {
	return predicate.Object(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v uint32) predicate.Object {
	return predicate.Object(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...uint32) predicate.Object {
	return predicate.Object(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...uint32) predicate.Object {
	return predicate.Object(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v uint32) predicate.Object {
	return predicate.Object(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v uint32) predicate.Object {
	return predicate.Object(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v uint32) predicate.Object {
	return predicate.Object(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v uint32) predicate.Object {
	return predicate.Object(sql.FieldLTE(FieldType, v))
}

// HasArchive applies the HasEdge predicate on the "archive" edge.
func HasArchive() predicate.Object {
	return predicate.Object(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ArchiveTable, ArchiveColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArchiveWith applies the HasEdge predicate on the "archive" edge with a given conditions (other predicates).
func HasArchiveWith(preds ...predicate.Archive) predicate.Object {
	return predicate.Object(func(s *sql.Selector) {
		step := newArchiveStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Object) predicate.Object {
	return predicate.Object(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Object) predicate.Object {
	return predicate.Object(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Object) predicate.Object {
	return predicate.Object(sql.NotPredicates(p))
}
