version: '3'
volumes:
  pgdata:
services:
  postgres:
    image: postgres:12.1
    restart: unless-stopped
    ports:
    - 6655:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
  cockroach:
    image: cockroachdb/cockroach:latest-v21.1
    command:
      - start-single-node
      - --insecure
    ports:
      - 26257:26257
      - 26258:8080