// Code generated by ent, DO NOT EDIT.

package publicref

import (
	"entgo.io/ent/dialect/sql"
	"github.com/twcclan/goback/index/sql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldLTE(FieldID, id))
}

// Ref applies equality check predicate on the "ref" field. It's identical to RefEQ.
func Ref(v []byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldEQ(FieldRef, v))
}

// RefEQ applies the EQ predicate on the "ref" field.
func RefEQ(v []byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldEQ(FieldRef, v))
}

// RefNEQ applies the NEQ predicate on the "ref" field.
func RefNEQ(v []byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldNEQ(FieldRef, v))
}

// RefIn applies the In predicate on the "ref" field.
func RefIn(vs ...[]byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldIn(FieldRef, vs...))
}

// RefNotIn applies the NotIn predicate on the "ref" field.
func RefNotIn(vs ...[]byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldNotIn(FieldRef, vs...))
}

// RefGT applies the GT predicate on the "ref" field.
func RefGT(v []byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldGT(FieldRef, v))
}

// RefGTE applies the GTE predicate on the "ref" field.
func RefGTE(v []byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldGTE(FieldRef, v))
}

// RefLT applies the LT predicate on the "ref" field.
func RefLT(v []byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldLT(FieldRef, v))
}

// RefLTE applies the LTE predicate on the "ref" field.
func RefLTE(v []byte) predicate.PublicRef {
	return predicate.PublicRef(sql.FieldLTE(FieldRef, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PublicRef) predicate.PublicRef {
	return predicate.PublicRef(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PublicRef) predicate.PublicRef {
	return predicate.PublicRef(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PublicRef) predicate.PublicRef {
	return predicate.PublicRef(sql.NotPredicates(p))
}
