// Code generated by ent, DO NOT EDIT.

package session

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gobackio/goback/index/sql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldID, id))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAgentID, v))
}

// BackupSet applies equality check predicate on the "backup_set" field. It's identical to BackupSetEQ.
func BackupSet(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldBackupSet, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStartedAt, v))
}

// LastSeen applies equality check predicate on the "last_seen" field. It's identical to LastSeenEQ.
func LastSeen(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldLastSeen, v))
}

// RestoreRef applies equality check predicate on the "restore_ref" field. It's identical to RestoreRefEQ.
func RestoreRef(v []byte) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldRestoreRef, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldAgentID, v))
}

// AgentIDContains applies the Contains predicate on the "agent_id" field.
func AgentIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldAgentID, v))
}

// AgentIDHasPrefix applies the HasPrefix predicate on the "agent_id" field.
func AgentIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldAgentID, v))
}

// AgentIDHasSuffix applies the HasSuffix predicate on the "agent_id" field.
func AgentIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldAgentID, v))
}

// AgentIDEqualFold applies the EqualFold predicate on the "agent_id" field.
func AgentIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldAgentID, v))
}

// AgentIDContainsFold applies the ContainsFold predicate on the "agent_id" field.
func AgentIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldAgentID, v))
}

// BackupSetEQ applies the EQ predicate on the "backup_set" field.
func BackupSetEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldBackupSet, v))
}

// BackupSetNEQ applies the NEQ predicate on the "backup_set" field.
func BackupSetNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldBackupSet, v))
}

// BackupSetIn applies the In predicate on the "backup_set" field.
func BackupSetIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldBackupSet, vs...))
}

// BackupSetNotIn applies the NotIn predicate on the "backup_set" field.
func BackupSetNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldBackupSet, vs...))
}

// BackupSetGT applies the GT predicate on the "backup_set" field.
func BackupSetGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldBackupSet, v))
}

// BackupSetGTE applies the GTE predicate on the "backup_set" field.
func BackupSetGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldBackupSet, v))
}

// BackupSetLT applies the LT predicate on the "backup_set" field.
func BackupSetLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldBackupSet, v))
}

// BackupSetLTE applies the LTE predicate on the "backup_set" field.
func BackupSetLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldBackupSet, v))
}

// BackupSetContains applies the Contains predicate on the "backup_set" field.
func BackupSetContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldBackupSet, v))
}

// BackupSetHasPrefix applies the HasPrefix predicate on the "backup_set" field.
func BackupSetHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldBackupSet, v))
}

// BackupSetHasSuffix applies the HasSuffix predicate on the "backup_set" field.
func BackupSetHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldBackupSet, v))
}

// BackupSetEqualFold applies the EqualFold predicate on the "backup_set" field.
func BackupSetEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldBackupSet, v))
}

// BackupSetContainsFold applies the ContainsFold predicate on the "backup_set" field.
func BackupSetContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldBackupSet, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldStartedAt, v))
}

// LastSeenEQ applies the EQ predicate on the "last_seen" field.
func LastSeenEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldLastSeen, v))
}

// LastSeenNEQ applies the NEQ predicate on the "last_seen" field.
func LastSeenNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldLastSeen, v))
}

// LastSeenIn applies the In predicate on the "last_seen" field.
func LastSeenIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldLastSeen, vs...))
}

// LastSeenNotIn applies the NotIn predicate on the "last_seen" field.
func LastSeenNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldLastSeen, vs...))
}

// LastSeenGT applies the GT predicate on the "last_seen" field.
func LastSeenGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldLastSeen, v))
}

// LastSeenGTE applies the GTE predicate on the "last_seen" field.
func LastSeenGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldLastSeen, v))
}

// LastSeenLT applies the LT predicate on the "last_seen" field.
func LastSeenLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldLastSeen, v))
}

// LastSeenLTE applies the LTE predicate on the "last_seen" field.
func LastSeenLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldLastSeen, v))
}

// RestoreRefEQ applies the EQ predicate on the "restore_ref" field.
func RestoreRefEQ(v []byte) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldRestoreRef, v))
}

// RestoreRefNEQ applies the NEQ predicate on the "restore_ref" field.
func RestoreRefNEQ(v []byte) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldRestoreRef, v))
}

// RestoreRefIn applies the In predicate on the "restore_ref" field.
func RestoreRefIn(vs ...[]byte) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldRestoreRef, vs...))
}

// RestoreRefNotIn applies the NotIn predicate on the "restore_ref" field.
func RestoreRefNotIn(vs ...[]byte) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldRestoreRef, vs...))
}

// RestoreRefGT applies the GT predicate on the "restore_ref" field.
func RestoreRefGT(v []byte) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldRestoreRef, v))
}

// RestoreRefGTE applies the GTE predicate on the "restore_ref" field.
func RestoreRefGTE(v []byte) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldRestoreRef, v))
}

// RestoreRefLT applies the LT predicate on the "restore_ref" field.
func RestoreRefLT(v []byte) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldRestoreRef, v))
}

// RestoreRefLTE applies the LTE predicate on the "restore_ref" field.
func RestoreRefLTE(v []byte) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldRestoreRef, v))
}

// RestoreRefIsNil applies the IsNil predicate on the "restore_ref" field.
func RestoreRefIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldRestoreRef))
}

// RestoreRefNotNil applies the NotNil predicate on the "restore_ref" field.
func RestoreRefNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldRestoreRef))
}

// HasArchives applies the HasEdge predicate on the "archives" edge.
func HasArchives() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ArchivesTable, ArchivesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArchivesWith applies the HasEdge predicate on the "archives" edge with a given conditions (other predicates).
func HasArchivesWith(preds ...predicate.Archive) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newArchivesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
