// Code generated by ent, DO NOT EDIT.

package deletedref

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the deletedref type in the database.
	Label = "deleted_ref"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRef holds the string denoting the ref field in the database.
	FieldRef = "ref"
	// FieldTombstonedAt holds the string denoting the tombstoned_at field in the database.
	FieldTombstonedAt = "tombstoned_at"
	// Table holds the table name of the deletedref in the database.
	Table = "deleted_refs"
)

// Columns holds all SQL columns for deletedref fields.
var Columns = []string{
	FieldID,
	FieldRef,
	FieldTombstonedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the DeletedRef queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTombstonedAt orders the results by the tombstoned_at field.
func ByTombstonedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTombstonedAt, opts...).ToFunc()
}
