// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: admin/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupSet struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AgentId string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// active, closing or deleted
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// the logical size of the newest live commit
	LogicalSize int64 `protobuf:"varint,5,opt,name=logical_size,json=logicalSize,proto3" json:"logical_size,omitempty"`
	// what the set's objects take up in the store, as of the last
	// garbage collection
	PhysicalSize  int64 `protobuf:"varint,6,opt,name=physical_size,json=physicalSize,proto3" json:"physical_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSet) Reset() {
	*x = BackupSet{}
	mi := &file_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSet) ProtoMessage() {}

func (x *BackupSet) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSet.ProtoReflect.Descriptor instead.
func (*BackupSet) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *BackupSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupSet) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BackupSet) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BackupSet) GetLogicalSize() int64 {
	if x != nil {
		return x.LogicalSize
	}
	return 0
}

func (x *BackupSet) GetPhysicalSize() int64 {
	if x != nil {
		return x.PhysicalSize
	}
	return 0
}

type ListSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSetsRequest) Reset() {
	*x = ListSetsRequest{}
	mi := &file_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetsRequest) ProtoMessage() {}

func (x *ListSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetsRequest.ProtoReflect.Descriptor instead.
func (*ListSetsRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{1}
}

type ListSetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sets          []*BackupSet           `protobuf:"bytes,1,rep,name=sets,proto3" json:"sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSetsResponse) Reset() {
	*x = ListSetsResponse{}
	mi := &file_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetsResponse) ProtoMessage() {}

func (x *ListSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetsResponse.ProtoReflect.Descriptor instead.
func (*ListSetsResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListSetsResponse) GetSets() []*BackupSet {
	if x != nil {
		return x.Sets
	}
	return nil
}

type TransferSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferSetRequest) Reset() {
	*x = TransferSetRequest{}
	mi := &file_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferSetRequest) ProtoMessage() {}

func (x *TransferSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferSetRequest.ProtoReflect.Descriptor instead.
func (*TransferSetRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *TransferSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransferSetRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeleteSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Erase         bool                   `protobuf:"varint,2,opt,name=erase,proto3" json:"erase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSetRequest) Reset() {
	*x = DeleteSetRequest{}
	mi := &file_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetRequest) ProtoMessage() {}

func (x *DeleteSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSetRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteSetRequest) GetErase() bool {
	if x != nil {
		return x.Erase
	}
	return false
}

type DeleteSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSetResponse) Reset() {
	*x = DeleteSetResponse{}
	mi := &file_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetResponse) ProtoMessage() {}

func (x *DeleteSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSetResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{5}
}

type UndeleteSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteSetRequest) Reset() {
	*x = UndeleteSetRequest{}
	mi := &file_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteSetRequest) ProtoMessage() {}

func (x *UndeleteSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteSetRequest.ProtoReflect.Descriptor instead.
func (*UndeleteSetRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UndeleteSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UndeleteSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteSetResponse) Reset() {
	*x = UndeleteSetResponse{}
	mi := &file_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteSetResponse) ProtoMessage() {}

func (x *UndeleteSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteSetResponse.ProtoReflect.Descriptor instead.
func (*UndeleteSetResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{7}
}

type StorePolicy struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// sealed or none
	Mode          string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	PresenceScope string `protobuf:"bytes,6,opt,name=presence_scope,json=presenceScope,proto3" json:"presence_scope,omitempty"`
	// when the operator confirmed the store key is saved
	KeyAcknowledgedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=key_acknowledged_at,json=keyAcknowledgedAt,proto3" json:"key_acknowledged_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StorePolicy) Reset() {
	*x = StorePolicy{}
	mi := &file_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePolicy) ProtoMessage() {}

func (x *StorePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorePolicy.ProtoReflect.Descriptor instead.
func (*StorePolicy) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *StorePolicy) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StorePolicy) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StorePolicy) GetPresenceScope() string {
	if x != nil {
		return x.PresenceScope
	}
	return ""
}

func (x *StorePolicy) GetKeyAcknowledgedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.KeyAcknowledgedAt
	}
	return nil
}

type GetStorePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorePolicyRequest) Reset() {
	*x = GetStorePolicyRequest{}
	mi := &file_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorePolicyRequest) ProtoMessage() {}

func (x *GetStorePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorePolicyRequest.ProtoReflect.Descriptor instead.
func (*GetStorePolicyRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{9}
}

type SetStorePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	PresenceScope string                 `protobuf:"bytes,5,opt,name=presence_scope,json=presenceScope,proto3" json:"presence_scope,omitempty"`
	// the operator confirms the store key is saved
	AcknowledgeKey bool `protobuf:"varint,7,opt,name=acknowledge_key,json=acknowledgeKey,proto3" json:"acknowledge_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetStorePolicyRequest) Reset() {
	*x = SetStorePolicyRequest{}
	mi := &file_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStorePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStorePolicyRequest) ProtoMessage() {}

func (x *SetStorePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStorePolicyRequest.ProtoReflect.Descriptor instead.
func (*SetStorePolicyRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{10}
}

func (x *SetStorePolicyRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SetStorePolicyRequest) GetPresenceScope() string {
	if x != nil {
		return x.PresenceScope
	}
	return ""
}

func (x *SetStorePolicyRequest) GetAcknowledgeKey() bool {
	if x != nil {
		return x.AcknowledgeKey
	}
	return false
}

// RetentionBracket keeps one commit per period over a stretch of a set's
// past. Brackets run consecutively, each starting where the one before
// it ended, so "for" is how long this bracket lasts rather than how old
// its commits may be.
type RetentionBracket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hourly, daily, weekly or monthly
	Period string `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	// seconds; zero is the tail, which lasts forever and so must be last
	ForSeconds    int64 `protobuf:"varint,2,opt,name=for_seconds,json=forSeconds,proto3" json:"for_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionBracket) Reset() {
	*x = RetentionBracket{}
	mi := &file_admin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionBracket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionBracket) ProtoMessage() {}

func (x *RetentionBracket) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionBracket.ProtoReflect.Descriptor instead.
func (*RetentionBracket) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *RetentionBracket) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *RetentionBracket) GetForSeconds() int64 {
	if x != nil {
		return x.ForSeconds
	}
	return 0
}

// RetentionPolicy keeps a commit while a bracket holds it, it is one of
// the last keep_last, or it is younger than keep_within.
type RetentionPolicy struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	KeepLast int32                  `protobuf:"varint,1,opt,name=keep_last,json=keepLast,proto3" json:"keep_last,omitempty"`
	// seconds
	KeepWithin    int64               `protobuf:"varint,6,opt,name=keep_within,json=keepWithin,proto3" json:"keep_within,omitempty"`
	Brackets      []*RetentionBracket `protobuf:"bytes,7,rep,name=brackets,proto3" json:"brackets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionPolicy) Reset() {
	*x = RetentionPolicy{}
	mi := &file_admin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionPolicy) ProtoMessage() {}

func (x *RetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionPolicy.ProtoReflect.Descriptor instead.
func (*RetentionPolicy) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RetentionPolicy) GetKeepLast() int32 {
	if x != nil {
		return x.KeepLast
	}
	return 0
}

func (x *RetentionPolicy) GetKeepWithin() int64 {
	if x != nil {
		return x.KeepWithin
	}
	return 0
}

func (x *RetentionPolicy) GetBrackets() []*RetentionBracket {
	if x != nil {
		return x.Brackets
	}
	return nil
}

type Retention struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the set, empty for the store's defaults
	Set string `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	// the policy set here; unset when a set inherits the store's or the
	// store runs the built-in default
	Policy *RetentionPolicy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// the policy in force after inheritance
	Effective *RetentionPolicy `protobuf:"bytes,3,opt,name=effective,proto3" json:"effective,omitempty"`
	// a rebuilt set keeps everything until a policy is set
	Paused bool `protobuf:"varint,4,opt,name=paused,proto3" json:"paused,omitempty"`
	// the store's windows before a retired or deleted commit is
	// tombstoned
	HoldDays      int32 `protobuf:"varint,5,opt,name=hold_days,json=holdDays,proto3" json:"hold_days,omitempty"`
	TrashDays     int32 `protobuf:"varint,6,opt,name=trash_days,json=trashDays,proto3" json:"trash_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Retention) Reset() {
	*x = Retention{}
	mi := &file_admin_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Retention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retention) ProtoMessage() {}

func (x *Retention) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retention.ProtoReflect.Descriptor instead.
func (*Retention) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{13}
}

func (x *Retention) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *Retention) GetPolicy() *RetentionPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Retention) GetEffective() *RetentionPolicy {
	if x != nil {
		return x.Effective
	}
	return nil
}

func (x *Retention) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *Retention) GetHoldDays() int32 {
	if x != nil {
		return x.HoldDays
	}
	return 0
}

func (x *Retention) GetTrashDays() int32 {
	if x != nil {
		return x.TrashDays
	}
	return 0
}

type GetRetentionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           string                 `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRetentionRequest) Reset() {
	*x = GetRetentionRequest{}
	mi := &file_admin_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetentionRequest) ProtoMessage() {}

func (x *GetRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetentionRequest.ProtoReflect.Descriptor instead.
func (*GetRetentionRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetRetentionRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

type SetRetentionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Set   string                 `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	// replaces the policy when set
	Policy *RetentionPolicy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// drops the policy: the set inherits, the store uses the built-in
	Inherit bool `protobuf:"varint,3,opt,name=inherit,proto3" json:"inherit,omitempty"`
	// the store's windows, ignored for a set
	HoldDays      *int32 `protobuf:"varint,4,opt,name=hold_days,json=holdDays,proto3,oneof" json:"hold_days,omitempty"`
	TrashDays     *int32 `protobuf:"varint,5,opt,name=trash_days,json=trashDays,proto3,oneof" json:"trash_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRetentionRequest) Reset() {
	*x = SetRetentionRequest{}
	mi := &file_admin_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRetentionRequest) ProtoMessage() {}

func (x *SetRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRetentionRequest.ProtoReflect.Descriptor instead.
func (*SetRetentionRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{15}
}

func (x *SetRetentionRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *SetRetentionRequest) GetPolicy() *RetentionPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SetRetentionRequest) GetInherit() bool {
	if x != nil {
		return x.Inherit
	}
	return false
}

func (x *SetRetentionRequest) GetHoldDays() int32 {
	if x != nil && x.HoldDays != nil {
		return *x.HoldDays
	}
	return 0
}

func (x *SetRetentionRequest) GetTrashDays() int32 {
	if x != nil && x.TrashDays != nil {
		return *x.TrashDays
	}
	return 0
}

type RetireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetireRequest) Reset() {
	*x = RetireRequest{}
	mi := &file_admin_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetireRequest) ProtoMessage() {}

func (x *RetireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetireRequest.ProtoReflect.Descriptor instead.
func (*RetireRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{16}
}

type RetireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retired       int64                  `protobuf:"varint,1,opt,name=retired,proto3" json:"retired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetireResponse) Reset() {
	*x = RetireResponse{}
	mi := &file_admin_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetireResponse) ProtoMessage() {}

func (x *RetireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetireResponse.ProtoReflect.Descriptor instead.
func (*RetireResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{17}
}

func (x *RetireResponse) GetRetired() int64 {
	if x != nil {
		return x.Retired
	}
	return 0
}

type CollectGarbageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectGarbageRequest) Reset() {
	*x = CollectGarbageRequest{}
	mi := &file_admin_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectGarbageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGarbageRequest) ProtoMessage() {}

func (x *CollectGarbageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGarbageRequest.ProtoReflect.Descriptor instead.
func (*CollectGarbageRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{18}
}

type CollectGarbageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        string                 `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectGarbageResponse) Reset() {
	*x = CollectGarbageResponse{}
	mi := &file_admin_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectGarbageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGarbageResponse) ProtoMessage() {}

func (x *CollectGarbageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGarbageResponse.ProtoReflect.Descriptor instead.
func (*CollectGarbageResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{19}
}

func (x *CollectGarbageResponse) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

type PutEscrowedKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	KeyId string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// the armored age file goback key escrow prints
	Escrowed      string `protobuf:"bytes,2,opt,name=escrowed,proto3" json:"escrowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutEscrowedKeyRequest) Reset() {
	*x = PutEscrowedKeyRequest{}
	mi := &file_admin_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEscrowedKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEscrowedKeyRequest) ProtoMessage() {}

func (x *PutEscrowedKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEscrowedKeyRequest.ProtoReflect.Descriptor instead.
func (*PutEscrowedKeyRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{20}
}

func (x *PutEscrowedKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PutEscrowedKeyRequest) GetEscrowed() string {
	if x != nil {
		return x.Escrowed
	}
	return ""
}

type PutEscrowedKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutEscrowedKeyResponse) Reset() {
	*x = PutEscrowedKeyResponse{}
	mi := &file_admin_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEscrowedKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEscrowedKeyResponse) ProtoMessage() {}

func (x *PutEscrowedKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEscrowedKeyResponse.ProtoReflect.Descriptor instead.
func (*PutEscrowedKeyResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_proto_rawDescGZIP(), []int{21}
}

var File_admin_admin_proto protoreflect.FileDescriptor

const file_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x11admin/admin.proto\x12\x05admin\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\tBackupSet\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12!\n" +
	"\flogical_size\x18\x05 \x01(\x03R\vlogicalSize\x12#\n" +
	"\rphysical_size\x18\x06 \x01(\x03R\fphysicalSizeJ\x04\b\x01\x10\x02\"\x11\n" +
	"\x0fListSetsRequest\"8\n" +
	"\x10ListSetsResponse\x12$\n" +
	"\x04sets\x18\x01 \x03(\v2\x10.admin.BackupSetR\x04sets\"C\n" +
	"\x12TransferSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"<\n" +
	"\x10DeleteSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05erase\x18\x02 \x01(\bR\x05erase\"\x13\n" +
	"\x11DeleteSetResponse\"(\n" +
	"\x12UndeleteSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13UndeleteSetResponse\"\xc6\x01\n" +
	"\vStorePolicy\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12%\n" +
	"\x0epresence_scope\x18\x06 \x01(\tR\rpresenceScope\x12J\n" +
	"\x13key_acknowledged_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11keyAcknowledgedAtJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\a\x10\b\"\x17\n" +
	"\x15GetStorePolicyRequest\"\x93\x01\n" +
	"\x15SetStorePolicyRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12%\n" +
	"\x0epresence_scope\x18\x05 \x01(\tR\rpresenceScope\x12'\n" +
	"\x0facknowledge_key\x18\a \x01(\bR\x0eacknowledgeKeyJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x06\x10\a\"K\n" +
	"\x10RetentionBracket\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x1f\n" +
	"\vfor_seconds\x18\x02 \x01(\x03R\n" +
	"forSeconds\"\x84\x01\n" +
	"\x0fRetentionPolicy\x12\x1b\n" +
	"\tkeep_last\x18\x01 \x01(\x05R\bkeepLast\x12\x1f\n" +
	"\vkeep_within\x18\x06 \x01(\x03R\n" +
	"keepWithin\x123\n" +
	"\bbrackets\x18\a \x03(\v2\x17.admin.RetentionBracketR\bbrackets\"\xd7\x01\n" +
	"\tRetention\x12\x10\n" +
	"\x03set\x18\x01 \x01(\tR\x03set\x12.\n" +
	"\x06policy\x18\x02 \x01(\v2\x16.admin.RetentionPolicyR\x06policy\x124\n" +
	"\teffective\x18\x03 \x01(\v2\x16.admin.RetentionPolicyR\teffective\x12\x16\n" +
	"\x06paused\x18\x04 \x01(\bR\x06paused\x12\x1b\n" +
	"\thold_days\x18\x05 \x01(\x05R\bholdDays\x12\x1d\n" +
	"\n" +
	"trash_days\x18\x06 \x01(\x05R\ttrashDays\"'\n" +
	"\x13GetRetentionRequest\x12\x10\n" +
	"\x03set\x18\x01 \x01(\tR\x03set\"\xd4\x01\n" +
	"\x13SetRetentionRequest\x12\x10\n" +
	"\x03set\x18\x01 \x01(\tR\x03set\x12.\n" +
	"\x06policy\x18\x02 \x01(\v2\x16.admin.RetentionPolicyR\x06policy\x12\x18\n" +
	"\ainherit\x18\x03 \x01(\bR\ainherit\x12 \n" +
	"\thold_days\x18\x04 \x01(\x05H\x00R\bholdDays\x88\x01\x01\x12\"\n" +
	"\n" +
	"trash_days\x18\x05 \x01(\x05H\x01R\ttrashDays\x88\x01\x01B\f\n" +
	"\n" +
	"_hold_daysB\r\n" +
	"\v_trash_days\"\x0f\n" +
	"\rRetireRequest\"*\n" +
	"\x0eRetireResponse\x12\x18\n" +
	"\aretired\x18\x01 \x01(\x03R\aretired\"\x17\n" +
	"\x15CollectGarbageRequest\"0\n" +
	"\x16CollectGarbageResponse\x12\x16\n" +
	"\x06report\x18\x01 \x01(\tR\x06report\"J\n" +
	"\x15PutEscrowedKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1a\n" +
	"\bescrowed\x18\x02 \x01(\tR\bescrowed\"\x18\n" +
	"\x16PutEscrowedKeyResponse2\xf5\x05\n" +
	"\x05Admin\x12=\n" +
	"\bListSets\x12\x16.admin.ListSetsRequest\x1a\x17.admin.ListSetsResponse\"\x00\x12<\n" +
	"\vTransferSet\x12\x19.admin.TransferSetRequest\x1a\x10.admin.BackupSet\"\x00\x12@\n" +
	"\tDeleteSet\x12\x17.admin.DeleteSetRequest\x1a\x18.admin.DeleteSetResponse\"\x00\x12F\n" +
	"\vUndeleteSet\x12\x19.admin.UndeleteSetRequest\x1a\x1a.admin.UndeleteSetResponse\"\x00\x12D\n" +
	"\x0eGetStorePolicy\x12\x1c.admin.GetStorePolicyRequest\x1a\x12.admin.StorePolicy\"\x00\x12D\n" +
	"\x0eSetStorePolicy\x12\x1c.admin.SetStorePolicyRequest\x1a\x12.admin.StorePolicy\"\x00\x12>\n" +
	"\fGetRetention\x12\x1a.admin.GetRetentionRequest\x1a\x10.admin.Retention\"\x00\x12>\n" +
	"\fSetRetention\x12\x1a.admin.SetRetentionRequest\x1a\x10.admin.Retention\"\x00\x127\n" +
	"\x06Retire\x12\x14.admin.RetireRequest\x1a\x15.admin.RetireResponse\"\x00\x12O\n" +
	"\x0eCollectGarbage\x12\x1c.admin.CollectGarbageRequest\x1a\x1d.admin.CollectGarbageResponse\"\x00\x12O\n" +
	"\x0ePutEscrowedKey\x12\x1c.admin.PutEscrowedKeyRequest\x1a\x1d.admin.PutEscrowedKeyResponse\"\x00B'Z%github.com/twcclan/goback/proto/adminb\x06proto3"

var (
	file_admin_admin_proto_rawDescOnce sync.Once
	file_admin_admin_proto_rawDescData []byte
)

func file_admin_admin_proto_rawDescGZIP() []byte {
	file_admin_admin_proto_rawDescOnce.Do(func() {
		file_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)))
	})
	return file_admin_admin_proto_rawDescData
}

var file_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_admin_admin_proto_goTypes = []any{
	(*BackupSet)(nil),              // 0: admin.BackupSet
	(*ListSetsRequest)(nil),        // 1: admin.ListSetsRequest
	(*ListSetsResponse)(nil),       // 2: admin.ListSetsResponse
	(*TransferSetRequest)(nil),     // 3: admin.TransferSetRequest
	(*DeleteSetRequest)(nil),       // 4: admin.DeleteSetRequest
	(*DeleteSetResponse)(nil),      // 5: admin.DeleteSetResponse
	(*UndeleteSetRequest)(nil),     // 6: admin.UndeleteSetRequest
	(*UndeleteSetResponse)(nil),    // 7: admin.UndeleteSetResponse
	(*StorePolicy)(nil),            // 8: admin.StorePolicy
	(*GetStorePolicyRequest)(nil),  // 9: admin.GetStorePolicyRequest
	(*SetStorePolicyRequest)(nil),  // 10: admin.SetStorePolicyRequest
	(*RetentionBracket)(nil),       // 11: admin.RetentionBracket
	(*RetentionPolicy)(nil),        // 12: admin.RetentionPolicy
	(*Retention)(nil),              // 13: admin.Retention
	(*GetRetentionRequest)(nil),    // 14: admin.GetRetentionRequest
	(*SetRetentionRequest)(nil),    // 15: admin.SetRetentionRequest
	(*RetireRequest)(nil),          // 16: admin.RetireRequest
	(*RetireResponse)(nil),         // 17: admin.RetireResponse
	(*CollectGarbageRequest)(nil),  // 18: admin.CollectGarbageRequest
	(*CollectGarbageResponse)(nil), // 19: admin.CollectGarbageResponse
	(*PutEscrowedKeyRequest)(nil),  // 20: admin.PutEscrowedKeyRequest
	(*PutEscrowedKeyResponse)(nil), // 21: admin.PutEscrowedKeyResponse
	(*timestamppb.Timestamp)(nil),  // 22: google.protobuf.Timestamp
}
var file_admin_admin_proto_depIdxs = []int32{
	0,  // 0: admin.ListSetsResponse.sets:type_name -> admin.BackupSet
	22, // 1: admin.StorePolicy.key_acknowledged_at:type_name -> google.protobuf.Timestamp
	11, // 2: admin.RetentionPolicy.brackets:type_name -> admin.RetentionBracket
	12, // 3: admin.Retention.policy:type_name -> admin.RetentionPolicy
	12, // 4: admin.Retention.effective:type_name -> admin.RetentionPolicy
	12, // 5: admin.SetRetentionRequest.policy:type_name -> admin.RetentionPolicy
	1,  // 6: admin.Admin.ListSets:input_type -> admin.ListSetsRequest
	3,  // 7: admin.Admin.TransferSet:input_type -> admin.TransferSetRequest
	4,  // 8: admin.Admin.DeleteSet:input_type -> admin.DeleteSetRequest
	6,  // 9: admin.Admin.UndeleteSet:input_type -> admin.UndeleteSetRequest
	9,  // 10: admin.Admin.GetStorePolicy:input_type -> admin.GetStorePolicyRequest
	10, // 11: admin.Admin.SetStorePolicy:input_type -> admin.SetStorePolicyRequest
	14, // 12: admin.Admin.GetRetention:input_type -> admin.GetRetentionRequest
	15, // 13: admin.Admin.SetRetention:input_type -> admin.SetRetentionRequest
	16, // 14: admin.Admin.Retire:input_type -> admin.RetireRequest
	18, // 15: admin.Admin.CollectGarbage:input_type -> admin.CollectGarbageRequest
	20, // 16: admin.Admin.PutEscrowedKey:input_type -> admin.PutEscrowedKeyRequest
	2,  // 17: admin.Admin.ListSets:output_type -> admin.ListSetsResponse
	0,  // 18: admin.Admin.TransferSet:output_type -> admin.BackupSet
	5,  // 19: admin.Admin.DeleteSet:output_type -> admin.DeleteSetResponse
	7,  // 20: admin.Admin.UndeleteSet:output_type -> admin.UndeleteSetResponse
	8,  // 21: admin.Admin.GetStorePolicy:output_type -> admin.StorePolicy
	8,  // 22: admin.Admin.SetStorePolicy:output_type -> admin.StorePolicy
	13, // 23: admin.Admin.GetRetention:output_type -> admin.Retention
	13, // 24: admin.Admin.SetRetention:output_type -> admin.Retention
	17, // 25: admin.Admin.Retire:output_type -> admin.RetireResponse
	19, // 26: admin.Admin.CollectGarbage:output_type -> admin.CollectGarbageResponse
	21, // 27: admin.Admin.PutEscrowedKey:output_type -> admin.PutEscrowedKeyResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_admin_proto_init() }
func file_admin_admin_proto_init() {
	if File_admin_admin_proto != nil {
		return
	}
	file_admin_admin_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_proto_rawDesc), len(file_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_proto_goTypes,
		DependencyIndexes: file_admin_admin_proto_depIdxs,
		MessageInfos:      file_admin_admin_proto_msgTypes,
	}.Build()
	File_admin_admin_proto = out.File
	file_admin_admin_proto_goTypes = nil
	file_admin_admin_proto_depIdxs = nil
}
