// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Put(*proto.Object) error
type PutRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Object *Object                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// the ref the client computed for object; the server rejects a mismatch
	Ref           *Ref `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PutRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

// Get(*proto.Ref) (*proto.Object, error)
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *Object                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

// Delete(*proto.Ref) error
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

// Walk(bool, proto.ObjectType, ObjectReceiver) error
type WalkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load          bool                   `protobuf:"varint,1,opt,name=load,proto3" json:"load,omitempty"`
	ObjectType    ObjectType             `protobuf:"varint,2,opt,name=objectType,proto3,enum=proto.ObjectType" json:"objectType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkRequest) Reset() {
	*x = WalkRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkRequest) ProtoMessage() {}

func (x *WalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkRequest.ProtoReflect.Descriptor instead.
func (*WalkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *WalkRequest) GetLoad() bool {
	if x != nil {
		return x.Load
	}
	return false
}

func (x *WalkRequest) GetObjectType() ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectType_INVALID
}

type WalkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ObjectHeader          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Object        *Object                `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkResponse) Reset() {
	*x = WalkResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkResponse) ProtoMessage() {}

func (x *WalkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkResponse.ProtoReflect.Descriptor instead.
func (*WalkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *WalkResponse) GetHeader() *ObjectHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WalkResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

// Has(context.Context, *proto.Ref) (bool, error)
type HasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasRequest) Reset() {
	*x = HasRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasRequest) ProtoMessage() {}

func (x *HasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasRequest.ProtoReflect.Descriptor instead.
func (*HasRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *HasRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type HasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Has           bool                   `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasResponse) Reset() {
	*x = HasResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasResponse) ProtoMessage() {}

func (x *HasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasResponse.ProtoReflect.Descriptor instead.
func (*HasResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *HasResponse) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

type FileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupSet     string                 `protobuf:"bytes,1,opt,name=backup_set,json=backupSet,proto3" json:"backup_set,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=notAfter,proto3" json:"notAfter,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoRequest) Reset() {
	*x = FileInfoRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRequest) ProtoMessage() {}

func (x *FileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRequest.ProtoReflect.Descriptor instead.
func (*FileInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *FileInfoRequest) GetBackupSet() string {
	if x != nil {
		return x.BackupSet
	}
	return ""
}

func (x *FileInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfoRequest) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *FileInfoRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*TreeNode            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoResponse) Reset() {
	*x = FileInfoResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoResponse) ProtoMessage() {}

func (x *FileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoResponse.ProtoReflect.Descriptor instead.
func (*FileInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *FileInfoResponse) GetFiles() []*TreeNode {
	if x != nil {
		return x.Files
	}
	return nil
}

type CommitInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupSet     string                 `protobuf:"bytes,1,opt,name=backup_set,json=backupSet,proto3" json:"backup_set,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=notAfter,proto3" json:"notAfter,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitInfoRequest) Reset() {
	*x = CommitInfoRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitInfoRequest) ProtoMessage() {}

func (x *CommitInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitInfoRequest.ProtoReflect.Descriptor instead.
func (*CommitInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *CommitInfoRequest) GetBackupSet() string {
	if x != nil {
		return x.BackupSet
	}
	return ""
}

func (x *CommitInfoRequest) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CommitInfoRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CommitInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*Commit              `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitInfoResponse) Reset() {
	*x = CommitInfoResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitInfoResponse) ProtoMessage() {}

func (x *CommitInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitInfoResponse.ProtoReflect.Descriptor instead.
func (*CommitInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *CommitInfoResponse) GetCommits() []*Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

type LatestCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupSet     string                 `protobuf:"bytes,1,opt,name=backup_set,json=backupSet,proto3" json:"backup_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestCommitRequest) Reset() {
	*x = LatestCommitRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestCommitRequest) ProtoMessage() {}

func (x *LatestCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestCommitRequest.ProtoReflect.Descriptor instead.
func (*LatestCommitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *LatestCommitRequest) GetBackupSet() string {
	if x != nil {
		return x.BackupSet
	}
	return ""
}

type LatestCommitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty when the set has no commit
	Ref           *Ref `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestCommitResponse) Reset() {
	*x = LatestCommitResponse{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestCommitResponse) ProtoMessage() {}

func (x *LatestCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestCommitResponse.ProtoReflect.Descriptor instead.
func (*LatestCommitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *LatestCommitResponse) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetTreeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// how many directory levels below ref to include; 0 means only ref
	MaxDepth      uint32 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeRequest) Reset() {
	*x = GetTreeRequest{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeRequest) ProtoMessage() {}

func (x *GetTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeRequest.ProtoReflect.Descriptor instead.
func (*GetTreeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *GetTreeRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *GetTreeRequest) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type GetTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Object        *Object                `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeResponse) Reset() {
	*x = GetTreeResponse{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeResponse) ProtoMessage() {}

func (x *GetTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeResponse.ProtoReflect.Descriptor instead.
func (*GetTreeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *GetTreeResponse) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *GetTreeResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x05proto\x1a\fobject.proto\x1a\tref.proto\x1a\n" +
	"tree.proto\x1a\fcommit.proto\x1a\x13transactional.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\n" +
	"PutRequest\x12%\n" +
	"\x06object\x18\x01 \x01(\v2\r.proto.ObjectR\x06object\x12\x1c\n" +
	"\x03ref\x18\x02 \x01(\v2\n" +
	".proto.RefR\x03ref\"\r\n" +
	"\vPutResponse\"*\n" +
	"\n" +
	"GetRequest\x12\x1c\n" +
	"\x03ref\x18\x01 \x01(\v2\n" +
	".proto.RefR\x03ref\"4\n" +
	"\vGetResponse\x12%\n" +
	"\x06object\x18\x01 \x01(\v2\r.proto.ObjectR\x06object\"-\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\x03ref\x18\x01 \x01(\v2\n" +
	".proto.RefR\x03ref\"\x10\n" +
	"\x0eDeleteResponse\"T\n" +
	"\vWalkRequest\x12\x12\n" +
	"\x04load\x18\x01 \x01(\bR\x04load\x121\n" +
	"\n" +
	"objectType\x18\x02 \x01(\x0e2\x11.proto.ObjectTypeR\n" +
	"objectType\"b\n" +
	"\fWalkResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.proto.ObjectHeaderR\x06header\x12%\n" +
	"\x06object\x18\x02 \x01(\v2\r.proto.ObjectR\x06object\"*\n" +
	"\n" +
	"HasRequest\x12\x1c\n" +
	"\x03ref\x18\x01 \x01(\v2\n" +
	".proto.RefR\x03ref\"\x1f\n" +
	"\vHasResponse\x12\x10\n" +
	"\x03has\x18\x01 \x01(\bR\x03has\"\x92\x01\n" +
	"\x0fFileInfoRequest\x12\x1d\n" +
	"\n" +
	"backup_set\x18\x01 \x01(\tR\tbackupSet\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x126\n" +
	"\bnotAfter\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"9\n" +
	"\x10FileInfoResponse\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.proto.TreeNodeR\x05files\"\x80\x01\n" +
	"\x11CommitInfoRequest\x12\x1d\n" +
	"\n" +
	"backup_set\x18\x01 \x01(\tR\tbackupSet\x126\n" +
	"\bnotAfter\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"=\n" +
	"\x12CommitInfoResponse\x12'\n" +
	"\acommits\x18\x01 \x03(\v2\r.proto.CommitR\acommits\"4\n" +
	"\x13LatestCommitRequest\x12\x1d\n" +
	"\n" +
	"backup_set\x18\x01 \x01(\tR\tbackupSet\"4\n" +
	"\x14LatestCommitResponse\x12\x1c\n" +
	"\x03ref\x18\x01 \x01(\v2\n" +
	".proto.RefR\x03ref\"K\n" +
	"\x0eGetTreeRequest\x12\x1c\n" +
	"\x03ref\x18\x01 \x01(\v2\n" +
	".proto.RefR\x03ref\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\rR\bmaxDepth\"V\n" +
	"\x0fGetTreeResponse\x12\x1c\n" +
	"\x03ref\x18\x01 \x01(\v2\n" +
	".proto.RefR\x03ref\x12%\n" +
	"\x06object\x18\x02 \x01(\v2\r.proto.ObjectR\x06object2\x92\x04\n" +
	"\x05Store\x12.\n" +
	"\x03Put\x12\x11.proto.PutRequest\x1a\x12.proto.PutResponse\"\x00\x12.\n" +
	"\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\"\x00\x127\n" +
	"\x06Delete\x12\x14.proto.DeleteRequest\x1a\x15.proto.DeleteResponse\"\x00\x123\n" +
	"\x04Walk\x12\x12.proto.WalkRequest\x1a\x13.proto.WalkResponse\"\x000\x01\x12.\n" +
	"\x03Has\x12\x11.proto.HasRequest\x1a\x12.proto.HasResponse\"\x00\x12=\n" +
	"\bFileInfo\x12\x16.proto.FileInfoRequest\x1a\x17.proto.FileInfoResponse\"\x00\x12C\n" +
	"\n" +
	"CommitInfo\x12\x18.proto.CommitInfoRequest\x1a\x19.proto.CommitInfoResponse\"\x00\x12I\n" +
	"\fLatestCommit\x12\x1a.proto.LatestCommitRequest\x1a\x1b.proto.LatestCommitResponse\"\x00\x12<\n" +
	"\aGetTree\x12\x15.proto.GetTreeRequest\x1a\x16.proto.GetTreeResponse\"\x000\x01B!Z\x1fgithub.com/twcclan/goback/protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_goTypes = []any{
	(*PutRequest)(nil),            // 0: proto.PutRequest
	(*PutResponse)(nil),           // 1: proto.PutResponse
	(*GetRequest)(nil),            // 2: proto.GetRequest
	(*GetResponse)(nil),           // 3: proto.GetResponse
	(*DeleteRequest)(nil),         // 4: proto.DeleteRequest
	(*DeleteResponse)(nil),        // 5: proto.DeleteResponse
	(*WalkRequest)(nil),           // 6: proto.WalkRequest
	(*WalkResponse)(nil),          // 7: proto.WalkResponse
	(*HasRequest)(nil),            // 8: proto.HasRequest
	(*HasResponse)(nil),           // 9: proto.HasResponse
	(*FileInfoRequest)(nil),       // 10: proto.FileInfoRequest
	(*FileInfoResponse)(nil),      // 11: proto.FileInfoResponse
	(*CommitInfoRequest)(nil),     // 12: proto.CommitInfoRequest
	(*CommitInfoResponse)(nil),    // 13: proto.CommitInfoResponse
	(*LatestCommitRequest)(nil),   // 14: proto.LatestCommitRequest
	(*LatestCommitResponse)(nil),  // 15: proto.LatestCommitResponse
	(*GetTreeRequest)(nil),        // 16: proto.GetTreeRequest
	(*GetTreeResponse)(nil),       // 17: proto.GetTreeResponse
	(*Object)(nil),                // 18: proto.Object
	(*Ref)(nil),                   // 19: proto.Ref
	(ObjectType)(0),               // 20: proto.ObjectType
	(*ObjectHeader)(nil),          // 21: proto.ObjectHeader
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(*TreeNode)(nil),              // 23: proto.TreeNode
	(*Commit)(nil),                // 24: proto.Commit
}
var file_api_proto_depIdxs = []int32{
	18, // 0: proto.PutRequest.object:type_name -> proto.Object
	19, // 1: proto.PutRequest.ref:type_name -> proto.Ref
	19, // 2: proto.GetRequest.ref:type_name -> proto.Ref
	18, // 3: proto.GetResponse.object:type_name -> proto.Object
	19, // 4: proto.DeleteRequest.ref:type_name -> proto.Ref
	20, // 5: proto.WalkRequest.objectType:type_name -> proto.ObjectType
	21, // 6: proto.WalkResponse.header:type_name -> proto.ObjectHeader
	18, // 7: proto.WalkResponse.object:type_name -> proto.Object
	19, // 8: proto.HasRequest.ref:type_name -> proto.Ref
	22, // 9: proto.FileInfoRequest.notAfter:type_name -> google.protobuf.Timestamp
	23, // 10: proto.FileInfoResponse.files:type_name -> proto.TreeNode
	22, // 11: proto.CommitInfoRequest.notAfter:type_name -> google.protobuf.Timestamp
	24, // 12: proto.CommitInfoResponse.commits:type_name -> proto.Commit
	19, // 13: proto.LatestCommitResponse.ref:type_name -> proto.Ref
	19, // 14: proto.GetTreeRequest.ref:type_name -> proto.Ref
	19, // 15: proto.GetTreeResponse.ref:type_name -> proto.Ref
	18, // 16: proto.GetTreeResponse.object:type_name -> proto.Object
	0,  // 17: proto.Store.Put:input_type -> proto.PutRequest
	2,  // 18: proto.Store.Get:input_type -> proto.GetRequest
	4,  // 19: proto.Store.Delete:input_type -> proto.DeleteRequest
	6,  // 20: proto.Store.Walk:input_type -> proto.WalkRequest
	8,  // 21: proto.Store.Has:input_type -> proto.HasRequest
	10, // 22: proto.Store.FileInfo:input_type -> proto.FileInfoRequest
	12, // 23: proto.Store.CommitInfo:input_type -> proto.CommitInfoRequest
	14, // 24: proto.Store.LatestCommit:input_type -> proto.LatestCommitRequest
	16, // 25: proto.Store.GetTree:input_type -> proto.GetTreeRequest
	1,  // 26: proto.Store.Put:output_type -> proto.PutResponse
	3,  // 27: proto.Store.Get:output_type -> proto.GetResponse
	5,  // 28: proto.Store.Delete:output_type -> proto.DeleteResponse
	7,  // 29: proto.Store.Walk:output_type -> proto.WalkResponse
	9,  // 30: proto.Store.Has:output_type -> proto.HasResponse
	11, // 31: proto.Store.FileInfo:output_type -> proto.FileInfoResponse
	13, // 32: proto.Store.CommitInfo:output_type -> proto.CommitInfoResponse
	15, // 33: proto.Store.LatestCommit:output_type -> proto.LatestCommitResponse
	17, // 34: proto.Store.GetTree:output_type -> proto.GetTreeResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_object_proto_init()
	file_ref_proto_init()
	file_tree_proto_init()
	file_commit_proto_init()
	file_transactional_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
