// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Put(*proto.Object) error
type PutRequest struct {
	Object               *Object  `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{0}
}
func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (dst *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(dst, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type PutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{1}
}
func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (dst *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(dst, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

// Get(*proto.Ref) (*proto.Object, error)
type GetRequest struct {
	Ref                  *Ref     `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetRef() *Ref {
	if m != nil {
		return m.Ref
	}
	return nil
}

type GetResponse struct {
	Object               *Object  `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{3}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

// Delete(*proto.Ref) error
type DeleteRequest struct {
	Ref                  *Ref     `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{4}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetRef() *Ref {
	if m != nil {
		return m.Ref
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{5}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

// Walk(bool, proto.ObjectType, ObjectReceiver) error
type WalkRequest struct {
	Load                 bool       `protobuf:"varint,1,opt,name=load,proto3" json:"load,omitempty"`
	ObjectType           ObjectType `protobuf:"varint,2,opt,name=objectType,proto3,enum=proto.ObjectType" json:"objectType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WalkRequest) Reset()         { *m = WalkRequest{} }
func (m *WalkRequest) String() string { return proto.CompactTextString(m) }
func (*WalkRequest) ProtoMessage()    {}
func (*WalkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{6}
}
func (m *WalkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalkRequest.Unmarshal(m, b)
}
func (m *WalkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalkRequest.Marshal(b, m, deterministic)
}
func (dst *WalkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalkRequest.Merge(dst, src)
}
func (m *WalkRequest) XXX_Size() int {
	return xxx_messageInfo_WalkRequest.Size(m)
}
func (m *WalkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WalkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WalkRequest proto.InternalMessageInfo

func (m *WalkRequest) GetLoad() bool {
	if m != nil {
		return m.Load
	}
	return false
}

func (m *WalkRequest) GetObjectType() ObjectType {
	if m != nil {
		return m.ObjectType
	}
	return ObjectType_INVALID
}

type WalkResponse struct {
	Header               *ObjectHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Object               *Object       `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WalkResponse) Reset()         { *m = WalkResponse{} }
func (m *WalkResponse) String() string { return proto.CompactTextString(m) }
func (*WalkResponse) ProtoMessage()    {}
func (*WalkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{7}
}
func (m *WalkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalkResponse.Unmarshal(m, b)
}
func (m *WalkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalkResponse.Marshal(b, m, deterministic)
}
func (dst *WalkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalkResponse.Merge(dst, src)
}
func (m *WalkResponse) XXX_Size() int {
	return xxx_messageInfo_WalkResponse.Size(m)
}
func (m *WalkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WalkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WalkResponse proto.InternalMessageInfo

func (m *WalkResponse) GetHeader() *ObjectHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *WalkResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

// Has(context.Context, *proto.Ref) (bool, error)
type HasRequest struct {
	Ref                  *Ref     `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasRequest) Reset()         { *m = HasRequest{} }
func (m *HasRequest) String() string { return proto.CompactTextString(m) }
func (*HasRequest) ProtoMessage()    {}
func (*HasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{8}
}
func (m *HasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasRequest.Unmarshal(m, b)
}
func (m *HasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasRequest.Marshal(b, m, deterministic)
}
func (dst *HasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasRequest.Merge(dst, src)
}
func (m *HasRequest) XXX_Size() int {
	return xxx_messageInfo_HasRequest.Size(m)
}
func (m *HasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasRequest proto.InternalMessageInfo

func (m *HasRequest) GetRef() *Ref {
	if m != nil {
		return m.Ref
	}
	return nil
}

type HasResponse struct {
	Has                  bool     `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasResponse) Reset()         { *m = HasResponse{} }
func (m *HasResponse) String() string { return proto.CompactTextString(m) }
func (*HasResponse) ProtoMessage()    {}
func (*HasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d94d66842e8827d2, []int{9}
}
func (m *HasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasResponse.Unmarshal(m, b)
}
func (m *HasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasResponse.Marshal(b, m, deterministic)
}
func (dst *HasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasResponse.Merge(dst, src)
}
func (m *HasResponse) XXX_Size() int {
	return xxx_messageInfo_HasResponse.Size(m)
}
func (m *HasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasResponse proto.InternalMessageInfo

func (m *HasResponse) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "proto.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "proto.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
	proto.RegisterType((*WalkRequest)(nil), "proto.WalkRequest")
	proto.RegisterType((*WalkResponse)(nil), "proto.WalkResponse")
	proto.RegisterType((*HasRequest)(nil), "proto.HasRequest")
	proto.RegisterType((*HasResponse)(nil), "proto.HasResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Walk(ctx context.Context, in *WalkRequest, opts ...grpc.CallOption) (Store_WalkClient, error)
	Has(ctx context.Context, in *HasRequest, opts ...grpc.CallOption) (*HasResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/proto.Store/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/proto.Store/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.Store/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Walk(ctx context.Context, in *WalkRequest, opts ...grpc.CallOption) (Store_WalkClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Store_serviceDesc.Streams[0], "/proto.Store/Walk", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeWalkClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Store_WalkClient interface {
	Recv() (*WalkResponse, error)
	grpc.ClientStream
}

type storeWalkClient struct {
	grpc.ClientStream
}

func (x *storeWalkClient) Recv() (*WalkResponse, error) {
	m := new(WalkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeClient) Has(ctx context.Context, in *HasRequest, opts ...grpc.CallOption) (*HasResponse, error) {
	out := new(HasResponse)
	err := c.cc.Invoke(ctx, "/proto.Store/Has", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Walk(*WalkRequest, Store_WalkServer) error
	Has(context.Context, *HasRequest) (*HasResponse, error)
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Walk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WalkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServer).Walk(m, &storeWalkServer{stream})
}

type Store_WalkServer interface {
	Send(*WalkResponse) error
	grpc.ServerStream
}

type storeWalkServer struct {
	grpc.ServerStream
}

func (x *storeWalkServer) Send(m *WalkResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Store_Has_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Has(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Has",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Has(ctx, req.(*HasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Store_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Store_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Store_Delete_Handler,
		},
		{
			MethodName: "Has",
			Handler:    _Store_Has_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Walk",
			Handler:       _Store_Walk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_d94d66842e8827d2) }

var fileDescriptor_api_d94d66842e8827d2 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x5d, 0x4b, 0x02, 0x41,
	0x14, 0x75, 0xfd, 0x58, 0xf2, 0xac, 0x8a, 0x8d, 0x05, 0xb2, 0x04, 0xc9, 0x40, 0x20, 0x46, 0x52,
	0x1a, 0xf4, 0x07, 0x02, 0x7d, 0x4b, 0x26, 0xa1, 0xe7, 0x31, 0xaf, 0x58, 0x49, 0xbb, 0xed, 0x8e,
	0x0f, 0xfd, 0x80, 0xfe, 0x77, 0xec, 0xcc, 0xec, 0x57, 0x0f, 0xb1, 0x4f, 0x3b, 0x9c, 0x7b, 0xce,
	0xbd, 0xe7, 0xdc, 0xbb, 0x68, 0xcb, 0xf0, 0x6d, 0x1a, 0x46, 0x81, 0x0a, 0x58, 0x4b, 0x7f, 0xfc,
	0x4e, 0xb0, 0x79, 0xa7, 0x57, 0x65, 0x40, 0xbf, 0x1d, 0xd1, 0xce, 0x3c, 0xf9, 0x1c, 0x58, 0x1d,
	0x95, 0xa0, 0xaf, 0x23, 0xc5, 0x8a, 0x5d, 0xc1, 0x35, 0xc4, 0xa1, 0x33, 0x72, 0xc6, 0xde, 0xac,
	0x6b, 0x58, 0xd3, 0x27, 0x0d, 0x0a, 0x5b, 0xe4, 0x5d, 0x78, 0x5a, 0x14, 0x87, 0xc1, 0x67, 0x4c,
	0x7c, 0x02, 0x2c, 0x28, 0xeb, 0x71, 0x81, 0x46, 0x44, 0x3b, 0xdb, 0x00, 0xb6, 0x81, 0xa0, 0x9d,
	0x48, 0x60, 0x7e, 0x0f, 0x4f, 0x73, 0x8d, 0xb4, 0xea, 0xc0, 0x1b, 0x74, 0x1f, 0xe9, 0x40, 0x8a,
	0xaa, 0x0d, 0xe9, 0xa3, 0x97, 0xd2, 0xad, 0xc5, 0x35, 0xbc, 0x17, 0x79, 0xf8, 0x48, 0xe5, 0x0c,
	0xcd, 0x43, 0x20, 0xb7, 0x5a, 0x7f, 0x22, 0xf4, 0x9b, 0xdd, 0x01, 0x66, 0xda, 0xfa, 0x3b, 0xa4,
	0x61, 0x7d, 0xe4, 0x8c, 0x7b, 0xb3, 0xd3, 0x92, 0x9d, 0xa4, 0x20, 0x0a, 0x24, 0xbe, 0x41, 0xc7,
	0x74, 0xb5, 0x69, 0xae, 0xe1, 0xee, 0x49, 0x6e, 0x29, 0xb2, 0xc6, 0x06, 0x25, 0xf9, 0x52, 0x97,
	0x84, 0xa5, 0x14, 0xa2, 0xd7, 0xff, 0x8b, 0x3e, 0x01, 0x96, 0x32, 0xae, 0x96, 0xfb, 0x12, 0x9e,
	0xe6, 0x5a, 0x3b, 0x7d, 0x34, 0xf6, 0x32, 0xb6, 0x21, 0x93, 0xe7, 0xec, 0xa7, 0x8e, 0xd6, 0xb3,
	0x0a, 0x22, 0x62, 0x53, 0x34, 0x56, 0x47, 0xc5, 0xd2, 0x80, 0xf9, 0x3f, 0xe0, 0xb3, 0x22, 0x64,
	0xd7, 0x57, 0x4b, 0xf8, 0x0b, 0xca, 0xf9, 0xf9, 0xbd, 0x33, 0x7e, 0xe1, 0xac, 0xbc, 0xc6, 0x1e,
	0xe0, 0x9a, 0x13, 0xb0, 0x33, 0x5b, 0x2f, 0x1d, 0xd0, 0x3f, 0xff, 0x83, 0x66, 0xc2, 0x39, 0x9a,
	0xc9, 0x4e, 0x59, 0xda, 0xb6, 0x70, 0x36, 0x7f, 0x50, 0xc2, 0x52, 0xc9, 0xad, 0x93, 0xb8, 0x5b,
	0xca, 0x38, 0x73, 0x97, 0x2f, 0x2c, 0x73, 0x57, 0xd8, 0x0b, 0xaf, 0x6d, 0x5c, 0x0d, 0xce, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x44, 0xef, 0x8a, 0x6c, 0x29, 0x03, 0x00, 0x00,
}
