// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: file.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeType says what kind of filesystem entry a tree node describes.
type NodeType int32

const (
	NodeType_NODE_FILE      NodeType = 0
	NodeType_NODE_DIRECTORY NodeType = 1
	NodeType_NODE_SYMLINK   NodeType = 2
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_FILE",
		1: "NODE_DIRECTORY",
		2: "NODE_SYMLINK",
	}
	NodeType_value = map[string]int32{
		"NODE_FILE":      0,
		"NODE_DIRECTORY": 1,
		"NODE_SYMLINK":   2,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

// Chunker names the boundary function and parameters that cut a file.
type Chunker int32

const (
	// FastCDC with a 16 KiB minimum, 64 KiB target and 256 KiB maximum
	Chunker_FASTCDC_64K Chunker = 0
)

// Enum value maps for Chunker.
var (
	Chunker_name = map[int32]string{
		0: "FASTCDC_64K",
	}
	Chunker_value = map[string]int32{
		"FASTCDC_64K": 0,
	}
)

func (x Chunker) Enum() *Chunker {
	p := new(Chunker)
	*p = x
	return p
}

func (x Chunker) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Chunker) Descriptor() protoreflect.EnumDescriptor {
	return file_file_proto_enumTypes[1].Descriptor()
}

func (Chunker) Type() protoreflect.EnumType {
	return &file_file_proto_enumTypes[1]
}

func (x Chunker) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Chunker.Descriptor instead.
func (Chunker) EnumDescriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

// this contains file metadata, which can be different
// accross backups, even if file content is the same
// Name, user, group and link_target are plaintext bytes in an unencrypted
// store and deterministic tokens under the store key otherwise.
type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  []byte                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode  uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	User  []byte                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Group []byte                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Size  int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	// modification time in nanoseconds since the Unix epoch
	MtimeNs int64    `protobuf:"varint,8,opt,name=mtime_ns,json=mtimeNs,proto3" json:"mtime_ns,omitempty"`
	Type    NodeType `protobuf:"varint,9,opt,name=type,proto3,enum=proto.NodeType" json:"type,omitempty"`
	// the target of a symlink, empty for every other type
	LinkTarget    []byte `protobuf:"bytes,10,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *FileInfo) GetGroup() []byte {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMtimeNs() int64 {
	if x != nil {
		return x.MtimeNs
	}
	return 0
}

func (x *FileInfo) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_FILE
}

func (x *FileInfo) GetLinkTarget() []byte {
	if x != nil {
		return x.LinkTarget
	}
	return nil
}

type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// an ordered list of file parts
	Parts []*FilePart `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	// an ordered list of references to other file objects, which together
	// hold the file's parts
	Splits []*Ref `protobuf:"bytes,2,rep,name=splits,proto3" json:"splits,omitempty"`
	// the chunker that cut the parts
	Chunker Chunker `protobuf:"varint,3,opt,name=chunker,proto3,enum=proto.Chunker" json:"chunker,omitempty"`
	// the whole content of a small file, stored without a blob; sealed
	// under the store key when the store is encrypted
	Inline []byte `protobuf:"bytes,4,opt,name=inline,proto3" json:"inline,omitempty"`
	// how inline is stored
	InlineEncryption Encryption `protobuf:"varint,6,opt,name=inline_encryption,json=inlineEncryption,proto3,enum=proto.Encryption" json:"inline_encryption,omitempty"`
	// the content bytes under each split, in order, so a read finds the
	// split holding an offset without loading the others; absent in a file
	// written before splits were measured
	SplitLengths []uint64 `protobuf:"varint,7,rep,packed,name=split_lengths,json=splitLengths,proto3" json:"split_lengths,omitempty"`
	// how many levels of splits lie below this one: 1 when the splits hold
	// parts, more when they are split themselves; 0 without split_lengths
	SplitDepth    uint32 `protobuf:"varint,8,opt,name=split_depth,json=splitDepth,proto3" json:"split_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetParts() []*FilePart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *File) GetSplits() []*Ref {
	if x != nil {
		return x.Splits
	}
	return nil
}

func (x *File) GetChunker() Chunker {
	if x != nil {
		return x.Chunker
	}
	return Chunker_FASTCDC_64K
}

func (x *File) GetInline() []byte {
	if x != nil {
		return x.Inline
	}
	return nil
}

func (x *File) GetInlineEncryption() Encryption {
	if x != nil {
		return x.InlineEncryption
	}
	return Encryption_PLAINTEXT
}

func (x *File) GetSplitLengths() []uint64 {
	if x != nil {
		return x.SplitLengths
	}
	return nil
}

func (x *File) GetSplitDepth() uint32 {
	if x != nil {
		return x.SplitDepth
	}
	return 0
}

type FilePart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Ref           *Ref                   `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *FilePart) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FilePart) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FilePart) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\x05proto\x1a\tref.proto\x1a\x10encryption.proto\"\xee\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04user\x18\x03 \x01(\fR\x04user\x12\x14\n" +
	"\x05group\x18\x04 \x01(\fR\x05group\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x19\n" +
	"\bmtime_ns\x18\b \x01(\x03R\amtimeNs\x12#\n" +
	"\x04type\x18\t \x01(\x0e2\x0f.proto.NodeTypeR\x04type\x12\x1f\n" +
	"\vlink_target\x18\n" +
	" \x01(\fR\n" +
	"linkTargetJ\x04\b\x05\x10\x06J\x04\b\a\x10\bR\ttimestampR\x04tree\"\xa5\x02\n" +
	"\x04File\x12%\n" +
	"\x05parts\x18\x01 \x03(\v2\x0f.proto.FilePartR\x05parts\x12\"\n" +
	"\x06splits\x18\x02 \x03(\v2\n" +
	".proto.RefR\x06splits\x12(\n" +
	"\achunker\x18\x03 \x01(\x0e2\x0e.proto.ChunkerR\achunker\x12\x16\n" +
	"\x06inline\x18\x04 \x01(\fR\x06inline\x12>\n" +
	"\x11inline_encryption\x18\x06 \x01(\x0e2\x11.proto.EncryptionR\x10inlineEncryption\x12#\n" +
	"\rsplit_lengths\x18\a \x03(\x04R\fsplitLengths\x12\x1f\n" +
	"\vsplit_depth\x18\b \x01(\rR\n" +
	"splitDepthJ\x04\b\x05\x10\x06R\x04keys\"X\n" +
	"\bFilePart\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x1c\n" +
	"\x03ref\x18\x03 \x01(\v2\n" +
	".proto.RefR\x03ref*?\n" +
	"\bNodeType\x12\r\n" +
	"\tNODE_FILE\x10\x00\x12\x12\n" +
	"\x0eNODE_DIRECTORY\x10\x01\x12\x10\n" +
	"\fNODE_SYMLINK\x10\x02*\x1a\n" +
	"\aChunker\x12\x0f\n" +
	"\vFASTCDC_64K\x10\x00B!Z\x1fgithub.com/twcclan/goback/protob\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_file_proto_goTypes = []any{
	(NodeType)(0),    // 0: proto.NodeType
	(Chunker)(0),     // 1: proto.Chunker
	(*FileInfo)(nil), // 2: proto.FileInfo
	(*File)(nil),     // 3: proto.File
	(*FilePart)(nil), // 4: proto.FilePart
	(*Ref)(nil),      // 5: proto.Ref
	(Encryption)(0),  // 6: proto.Encryption
}
var file_file_proto_depIdxs = []int32{
	0, // 0: proto.FileInfo.type:type_name -> proto.NodeType
	4, // 1: proto.File.parts:type_name -> proto.FilePart
	5, // 2: proto.File.splits:type_name -> proto.Ref
	1, // 3: proto.File.chunker:type_name -> proto.Chunker
	6, // 4: proto.File.inline_encryption:type_name -> proto.Encryption
	5, // 5: proto.FilePart.ref:type_name -> proto.Ref
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	file_ref_proto_init()
	file_encryption_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		EnumInfos:         file_file_proto_enumTypes,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
