// Code generated by ent, DO NOT EDIT.

package setref

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the setref type in the database.
	Label = "set_ref"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSetID holds the string denoting the set_id field in the database.
	FieldSetID = "set_id"
	// FieldRef holds the string denoting the ref field in the database.
	FieldRef = "ref"
	// EdgeSet holds the string denoting the set edge name in mutations.
	EdgeSet = "set"
	// Table holds the table name of the setref in the database.
	Table = "set_refs"
	// SetTable is the table that holds the set relation/edge.
	SetTable = "set_refs"
	// SetInverseTable is the table name for the Set entity.
	// It exists in this package in order to avoid circular dependency with the "set" package.
	SetInverseTable = "sets"
	// SetColumn is the table column denoting the set relation/edge.
	SetColumn = "set_id"
)

// Columns holds all SQL columns for setref fields.
var Columns = []string{
	FieldID,
	FieldSetID,
	FieldRef,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the SetRef queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySetID orders the results by the set_id field.
func BySetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSetID, opts...).ToFunc()
}

// BySetField orders the results by set field.
func BySetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSetStep(), sql.OrderByField(field, opts...))
	}
}
func newSetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SetTable, SetColumn),
	)
}
